-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_crc_process_blocks is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    crcTables_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_0_ce0 : OUT STD_LOGIC;
    crcTables_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_1_ce0 : OUT STD_LOGIC;
    crcTables_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_2_ce0 : OUT STD_LOGIC;
    crcTables_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_3_ce0 : OUT STD_LOGIC;
    crcTables_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_4_ce0 : OUT STD_LOGIC;
    crcTables_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_5_ce0 : OUT STD_LOGIC;
    crcTables_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_6_ce0 : OUT STD_LOGIC;
    crcTables_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_7_ce0 : OUT STD_LOGIC;
    crcTables_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_8_ce0 : OUT STD_LOGIC;
    crcTables_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_9_ce0 : OUT STD_LOGIC;
    crcTables_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_10_ce0 : OUT STD_LOGIC;
    crcTables_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_11_ce0 : OUT STD_LOGIC;
    crcTables_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_12_ce0 : OUT STD_LOGIC;
    crcTables_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_13_ce0 : OUT STD_LOGIC;
    crcTables_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_14_ce0 : OUT STD_LOGIC;
    crcTables_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_15_ce0 : OUT STD_LOGIC;
    crcTables_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    inByte0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte0_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte0_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte0_empty_n : IN STD_LOGIC;
    inByte0_read : OUT STD_LOGIC;
    inByte1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1_empty_n : IN STD_LOGIC;
    inByte1_read : OUT STD_LOGIC;
    inByte2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte2_empty_n : IN STD_LOGIC;
    inByte2_read : OUT STD_LOGIC;
    inByte3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte3_empty_n : IN STD_LOGIC;
    inByte3_read : OUT STD_LOGIC;
    inByte4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte4_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte4_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte4_empty_n : IN STD_LOGIC;
    inByte4_read : OUT STD_LOGIC;
    inByte5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte5_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte5_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte5_empty_n : IN STD_LOGIC;
    inByte5_read : OUT STD_LOGIC;
    inByte6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte6_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte6_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte6_empty_n : IN STD_LOGIC;
    inByte6_read : OUT STD_LOGIC;
    inByte7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte7_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte7_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte7_empty_n : IN STD_LOGIC;
    inByte7_read : OUT STD_LOGIC;
    inByte8_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte8_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte8_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte8_empty_n : IN STD_LOGIC;
    inByte8_read : OUT STD_LOGIC;
    inByte9_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte9_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte9_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte9_empty_n : IN STD_LOGIC;
    inByte9_read : OUT STD_LOGIC;
    inByte10_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte10_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte10_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte10_empty_n : IN STD_LOGIC;
    inByte10_read : OUT STD_LOGIC;
    inByte11_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte11_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte11_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte11_empty_n : IN STD_LOGIC;
    inByte11_read : OUT STD_LOGIC;
    inByte12_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte12_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte12_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte12_empty_n : IN STD_LOGIC;
    inByte12_read : OUT STD_LOGIC;
    inByte13_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte13_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte13_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte13_empty_n : IN STD_LOGIC;
    inByte13_read : OUT STD_LOGIC;
    inByte14_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte14_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte14_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte14_empty_n : IN STD_LOGIC;
    inByte14_read : OUT STD_LOGIC;
    inByte15_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte15_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte15_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte15_empty_n : IN STD_LOGIC;
    inByte15_read : OUT STD_LOGIC;
    crc_size_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    crc_size_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    crc_size_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    crc_size_empty_n : IN STD_LOGIC;
    crc_size_read : OUT STD_LOGIC;
    init_value_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    init_value_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    init_value_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    init_value_empty_n : IN STD_LOGIC;
    init_value_read : OUT STD_LOGIC;
    outStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    outStream_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    outStream_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    outStream_full_n : IN STD_LOGIC;
    outStream_write : OUT STD_LOGIC;
    numChunks_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    numChunks_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    numChunks_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    numChunks_empty_n : IN STD_LOGIC;
    numChunks_read : OUT STD_LOGIC;
    chunkSize_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    chunkSize_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    chunkSize_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    chunkSize_empty_n : IN STD_LOGIC;
    chunkSize_read : OUT STD_LOGIC;
    numChunks_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numChunks_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    numChunks_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    numChunks_c_full_n : IN STD_LOGIC;
    numChunks_c_write : OUT STD_LOGIC );
end;


architecture behav of calculate_crc_process_blocks is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal crc_size_blk_n : STD_LOGIC;
    signal init_value_blk_n : STD_LOGIC;
    signal outStream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal numChunks_blk_n : STD_LOGIC;
    signal chunkSize_blk_n : STD_LOGIC;
    signal numChunks_c_blk_n : STD_LOGIC;
    signal init_value_2_reg_472 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal crc_size_1_reg_477 : STD_LOGIC_VECTOR (31 downto 0);
    signal chunkSize_1_reg_482 : STD_LOGIC_VECTOR (31 downto 0);
    signal numChunks_2_reg_487 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln325_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln325_reg_492 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_497 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_lshr_cast_cast_reg_502 : STD_LOGIC_VECTOR (27 downto 0);
    signal p_lshr_f_cast_cast_reg_507 : STD_LOGIC_VECTOR (27 downto 0);
    signal mask_1_fu_379_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mask_1_reg_512 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal blocks_in_chunk_fu_398_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal blocks_in_chunk_reg_518 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln329_fu_417_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln329_reg_523 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_ap_start : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_ap_done : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_ap_idle : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_ap_ready : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte0_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte1_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte2_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte3_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte4_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte5_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte6_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte7_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte8_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte9_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte10_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte11_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte12_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte13_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte14_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_inByte15_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crc_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_blocks_Pipeline_block_loop_fu_199_crc_out_ap_vld : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_ap_idle : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_ap_ready : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte14_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte13_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte12_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte11_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte10_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte9_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte8_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte7_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte6_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte5_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte4_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte3_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte2_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte1_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte0_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_inByte15_read : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_ce0 : STD_LOGIC;
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_crc_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_crc_2_out_ap_vld : STD_LOGIC;
    signal grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln329_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal c_fu_148 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln329_fu_434_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_313_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_neg_fu_337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln326_fu_368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mask_fu_373_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_cast_cast_cast_fu_386_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_neg_t_fu_389_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_lshr_f_cast_cast_cast_fu_395_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln329_fu_405_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln_fu_409_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln311_fu_425_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_crc_process_blocks_Pipeline_block_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inByte0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte0_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte0_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte0_empty_n : IN STD_LOGIC;
        inByte0_read : OUT STD_LOGIC;
        inByte1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1_empty_n : IN STD_LOGIC;
        inByte1_read : OUT STD_LOGIC;
        inByte2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte2_empty_n : IN STD_LOGIC;
        inByte2_read : OUT STD_LOGIC;
        inByte3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte3_empty_n : IN STD_LOGIC;
        inByte3_read : OUT STD_LOGIC;
        inByte4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte4_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte4_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte4_empty_n : IN STD_LOGIC;
        inByte4_read : OUT STD_LOGIC;
        inByte5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte5_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte5_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte5_empty_n : IN STD_LOGIC;
        inByte5_read : OUT STD_LOGIC;
        inByte6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte6_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte6_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte6_empty_n : IN STD_LOGIC;
        inByte6_read : OUT STD_LOGIC;
        inByte7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte7_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte7_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte7_empty_n : IN STD_LOGIC;
        inByte7_read : OUT STD_LOGIC;
        inByte8_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte8_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte8_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte8_empty_n : IN STD_LOGIC;
        inByte8_read : OUT STD_LOGIC;
        inByte9_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte9_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte9_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte9_empty_n : IN STD_LOGIC;
        inByte9_read : OUT STD_LOGIC;
        inByte10_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte10_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte10_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte10_empty_n : IN STD_LOGIC;
        inByte10_read : OUT STD_LOGIC;
        inByte11_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte11_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte11_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte11_empty_n : IN STD_LOGIC;
        inByte11_read : OUT STD_LOGIC;
        inByte12_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte12_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte12_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte12_empty_n : IN STD_LOGIC;
        inByte12_read : OUT STD_LOGIC;
        inByte13_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte13_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte13_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte13_empty_n : IN STD_LOGIC;
        inByte13_read : OUT STD_LOGIC;
        inByte14_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte14_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte14_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte14_empty_n : IN STD_LOGIC;
        inByte14_read : OUT STD_LOGIC;
        inByte15_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte15_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte15_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte15_empty_n : IN STD_LOGIC;
        inByte15_read : OUT STD_LOGIC;
        init_value_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        blocks_in_chunk : IN STD_LOGIC_VECTOR (28 downto 0);
        crcTables_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_0_ce0 : OUT STD_LOGIC;
        crcTables_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_1_ce0 : OUT STD_LOGIC;
        crcTables_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_2_ce0 : OUT STD_LOGIC;
        crcTables_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_3_ce0 : OUT STD_LOGIC;
        crcTables_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_4_ce0 : OUT STD_LOGIC;
        crcTables_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_5_ce0 : OUT STD_LOGIC;
        crcTables_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_6_ce0 : OUT STD_LOGIC;
        crcTables_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_7_ce0 : OUT STD_LOGIC;
        crcTables_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_8_ce0 : OUT STD_LOGIC;
        crcTables_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_9_ce0 : OUT STD_LOGIC;
        crcTables_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_10_ce0 : OUT STD_LOGIC;
        crcTables_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_11_ce0 : OUT STD_LOGIC;
        crcTables_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_12_ce0 : OUT STD_LOGIC;
        crcTables_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_13_ce0 : OUT STD_LOGIC;
        crcTables_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_14_ce0 : OUT STD_LOGIC;
        crcTables_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_15_ce0 : OUT STD_LOGIC;
        crcTables_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mask_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        crc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        crc_out_ap_vld : OUT STD_LOGIC );
    end component;


    component calculate_crc_process_blocks_Pipeline_tail_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inByte14_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte14_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte14_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte14_empty_n : IN STD_LOGIC;
        inByte14_read : OUT STD_LOGIC;
        inByte13_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte13_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte13_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte13_empty_n : IN STD_LOGIC;
        inByte13_read : OUT STD_LOGIC;
        inByte12_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte12_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte12_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte12_empty_n : IN STD_LOGIC;
        inByte12_read : OUT STD_LOGIC;
        inByte11_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte11_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte11_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte11_empty_n : IN STD_LOGIC;
        inByte11_read : OUT STD_LOGIC;
        inByte10_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte10_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte10_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte10_empty_n : IN STD_LOGIC;
        inByte10_read : OUT STD_LOGIC;
        inByte9_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte9_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte9_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte9_empty_n : IN STD_LOGIC;
        inByte9_read : OUT STD_LOGIC;
        inByte8_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte8_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte8_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte8_empty_n : IN STD_LOGIC;
        inByte8_read : OUT STD_LOGIC;
        inByte7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte7_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte7_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte7_empty_n : IN STD_LOGIC;
        inByte7_read : OUT STD_LOGIC;
        inByte6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte6_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte6_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte6_empty_n : IN STD_LOGIC;
        inByte6_read : OUT STD_LOGIC;
        inByte5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte5_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte5_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte5_empty_n : IN STD_LOGIC;
        inByte5_read : OUT STD_LOGIC;
        inByte4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte4_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte4_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte4_empty_n : IN STD_LOGIC;
        inByte4_read : OUT STD_LOGIC;
        inByte3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte3_empty_n : IN STD_LOGIC;
        inByte3_read : OUT STD_LOGIC;
        inByte2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte2_empty_n : IN STD_LOGIC;
        inByte2_read : OUT STD_LOGIC;
        inByte1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1_empty_n : IN STD_LOGIC;
        inByte1_read : OUT STD_LOGIC;
        inByte0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte0_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte0_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte0_empty_n : IN STD_LOGIC;
        inByte0_read : OUT STD_LOGIC;
        inByte15_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte15_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte15_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte15_empty_n : IN STD_LOGIC;
        inByte15_read : OUT STD_LOGIC;
        crc_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        sub_ln329 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_0_ce0 : OUT STD_LOGIC;
        crcTables_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mask_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        crc_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        crc_2_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_process_blocks_Pipeline_block_loop_fu_199 : component calculate_crc_process_blocks_Pipeline_block_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_blocks_Pipeline_block_loop_fu_199_ap_start,
        ap_done => grp_process_blocks_Pipeline_block_loop_fu_199_ap_done,
        ap_idle => grp_process_blocks_Pipeline_block_loop_fu_199_ap_idle,
        ap_ready => grp_process_blocks_Pipeline_block_loop_fu_199_ap_ready,
        inByte0_dout => inByte0_dout,
        inByte0_num_data_valid => ap_const_lv7_0,
        inByte0_fifo_cap => ap_const_lv7_0,
        inByte0_empty_n => inByte0_empty_n,
        inByte0_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte0_read,
        inByte1_dout => inByte1_dout,
        inByte1_num_data_valid => ap_const_lv7_0,
        inByte1_fifo_cap => ap_const_lv7_0,
        inByte1_empty_n => inByte1_empty_n,
        inByte1_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte1_read,
        inByte2_dout => inByte2_dout,
        inByte2_num_data_valid => ap_const_lv7_0,
        inByte2_fifo_cap => ap_const_lv7_0,
        inByte2_empty_n => inByte2_empty_n,
        inByte2_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte2_read,
        inByte3_dout => inByte3_dout,
        inByte3_num_data_valid => ap_const_lv7_0,
        inByte3_fifo_cap => ap_const_lv7_0,
        inByte3_empty_n => inByte3_empty_n,
        inByte3_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte3_read,
        inByte4_dout => inByte4_dout,
        inByte4_num_data_valid => ap_const_lv7_0,
        inByte4_fifo_cap => ap_const_lv7_0,
        inByte4_empty_n => inByte4_empty_n,
        inByte4_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte4_read,
        inByte5_dout => inByte5_dout,
        inByte5_num_data_valid => ap_const_lv7_0,
        inByte5_fifo_cap => ap_const_lv7_0,
        inByte5_empty_n => inByte5_empty_n,
        inByte5_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte5_read,
        inByte6_dout => inByte6_dout,
        inByte6_num_data_valid => ap_const_lv7_0,
        inByte6_fifo_cap => ap_const_lv7_0,
        inByte6_empty_n => inByte6_empty_n,
        inByte6_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte6_read,
        inByte7_dout => inByte7_dout,
        inByte7_num_data_valid => ap_const_lv7_0,
        inByte7_fifo_cap => ap_const_lv7_0,
        inByte7_empty_n => inByte7_empty_n,
        inByte7_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte7_read,
        inByte8_dout => inByte8_dout,
        inByte8_num_data_valid => ap_const_lv7_0,
        inByte8_fifo_cap => ap_const_lv7_0,
        inByte8_empty_n => inByte8_empty_n,
        inByte8_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte8_read,
        inByte9_dout => inByte9_dout,
        inByte9_num_data_valid => ap_const_lv7_0,
        inByte9_fifo_cap => ap_const_lv7_0,
        inByte9_empty_n => inByte9_empty_n,
        inByte9_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte9_read,
        inByte10_dout => inByte10_dout,
        inByte10_num_data_valid => ap_const_lv7_0,
        inByte10_fifo_cap => ap_const_lv7_0,
        inByte10_empty_n => inByte10_empty_n,
        inByte10_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte10_read,
        inByte11_dout => inByte11_dout,
        inByte11_num_data_valid => ap_const_lv7_0,
        inByte11_fifo_cap => ap_const_lv7_0,
        inByte11_empty_n => inByte11_empty_n,
        inByte11_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte11_read,
        inByte12_dout => inByte12_dout,
        inByte12_num_data_valid => ap_const_lv7_0,
        inByte12_fifo_cap => ap_const_lv7_0,
        inByte12_empty_n => inByte12_empty_n,
        inByte12_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte12_read,
        inByte13_dout => inByte13_dout,
        inByte13_num_data_valid => ap_const_lv7_0,
        inByte13_fifo_cap => ap_const_lv7_0,
        inByte13_empty_n => inByte13_empty_n,
        inByte13_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte13_read,
        inByte14_dout => inByte14_dout,
        inByte14_num_data_valid => ap_const_lv7_0,
        inByte14_fifo_cap => ap_const_lv7_0,
        inByte14_empty_n => inByte14_empty_n,
        inByte14_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte14_read,
        inByte15_dout => inByte15_dout,
        inByte15_num_data_valid => ap_const_lv7_0,
        inByte15_fifo_cap => ap_const_lv7_0,
        inByte15_empty_n => inByte15_empty_n,
        inByte15_read => grp_process_blocks_Pipeline_block_loop_fu_199_inByte15_read,
        init_value_2 => init_value_2_reg_472,
        blocks_in_chunk => blocks_in_chunk_reg_518,
        crcTables_0_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_address0,
        crcTables_0_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_ce0,
        crcTables_0_q0 => crcTables_0_q0,
        crcTables_1_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_address0,
        crcTables_1_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_ce0,
        crcTables_1_q0 => crcTables_1_q0,
        crcTables_2_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_address0,
        crcTables_2_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_ce0,
        crcTables_2_q0 => crcTables_2_q0,
        crcTables_3_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_address0,
        crcTables_3_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_ce0,
        crcTables_3_q0 => crcTables_3_q0,
        crcTables_4_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_address0,
        crcTables_4_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_ce0,
        crcTables_4_q0 => crcTables_4_q0,
        crcTables_5_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_address0,
        crcTables_5_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_ce0,
        crcTables_5_q0 => crcTables_5_q0,
        crcTables_6_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_address0,
        crcTables_6_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_ce0,
        crcTables_6_q0 => crcTables_6_q0,
        crcTables_7_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_address0,
        crcTables_7_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_ce0,
        crcTables_7_q0 => crcTables_7_q0,
        crcTables_8_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_address0,
        crcTables_8_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_ce0,
        crcTables_8_q0 => crcTables_8_q0,
        crcTables_9_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_address0,
        crcTables_9_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_ce0,
        crcTables_9_q0 => crcTables_9_q0,
        crcTables_10_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_address0,
        crcTables_10_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_ce0,
        crcTables_10_q0 => crcTables_10_q0,
        crcTables_11_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_address0,
        crcTables_11_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_ce0,
        crcTables_11_q0 => crcTables_11_q0,
        crcTables_12_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_address0,
        crcTables_12_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_ce0,
        crcTables_12_q0 => crcTables_12_q0,
        crcTables_13_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_address0,
        crcTables_13_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_ce0,
        crcTables_13_q0 => crcTables_13_q0,
        crcTables_14_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_address0,
        crcTables_14_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_ce0,
        crcTables_14_q0 => crcTables_14_q0,
        crcTables_15_address0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_address0,
        crcTables_15_ce0 => grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_ce0,
        crcTables_15_q0 => crcTables_15_q0,
        mask_1 => mask_1_reg_512,
        crc_out => grp_process_blocks_Pipeline_block_loop_fu_199_crc_out,
        crc_out_ap_vld => grp_process_blocks_Pipeline_block_loop_fu_199_crc_out_ap_vld);

    grp_process_blocks_Pipeline_tail_loop_fu_271 : component calculate_crc_process_blocks_Pipeline_tail_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start,
        ap_done => grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done,
        ap_idle => grp_process_blocks_Pipeline_tail_loop_fu_271_ap_idle,
        ap_ready => grp_process_blocks_Pipeline_tail_loop_fu_271_ap_ready,
        inByte14_dout => inByte14_dout,
        inByte14_num_data_valid => ap_const_lv7_0,
        inByte14_fifo_cap => ap_const_lv7_0,
        inByte14_empty_n => inByte14_empty_n,
        inByte14_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte14_read,
        inByte13_dout => inByte13_dout,
        inByte13_num_data_valid => ap_const_lv7_0,
        inByte13_fifo_cap => ap_const_lv7_0,
        inByte13_empty_n => inByte13_empty_n,
        inByte13_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte13_read,
        inByte12_dout => inByte12_dout,
        inByte12_num_data_valid => ap_const_lv7_0,
        inByte12_fifo_cap => ap_const_lv7_0,
        inByte12_empty_n => inByte12_empty_n,
        inByte12_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte12_read,
        inByte11_dout => inByte11_dout,
        inByte11_num_data_valid => ap_const_lv7_0,
        inByte11_fifo_cap => ap_const_lv7_0,
        inByte11_empty_n => inByte11_empty_n,
        inByte11_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte11_read,
        inByte10_dout => inByte10_dout,
        inByte10_num_data_valid => ap_const_lv7_0,
        inByte10_fifo_cap => ap_const_lv7_0,
        inByte10_empty_n => inByte10_empty_n,
        inByte10_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte10_read,
        inByte9_dout => inByte9_dout,
        inByte9_num_data_valid => ap_const_lv7_0,
        inByte9_fifo_cap => ap_const_lv7_0,
        inByte9_empty_n => inByte9_empty_n,
        inByte9_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte9_read,
        inByte8_dout => inByte8_dout,
        inByte8_num_data_valid => ap_const_lv7_0,
        inByte8_fifo_cap => ap_const_lv7_0,
        inByte8_empty_n => inByte8_empty_n,
        inByte8_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte8_read,
        inByte7_dout => inByte7_dout,
        inByte7_num_data_valid => ap_const_lv7_0,
        inByte7_fifo_cap => ap_const_lv7_0,
        inByte7_empty_n => inByte7_empty_n,
        inByte7_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte7_read,
        inByte6_dout => inByte6_dout,
        inByte6_num_data_valid => ap_const_lv7_0,
        inByte6_fifo_cap => ap_const_lv7_0,
        inByte6_empty_n => inByte6_empty_n,
        inByte6_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte6_read,
        inByte5_dout => inByte5_dout,
        inByte5_num_data_valid => ap_const_lv7_0,
        inByte5_fifo_cap => ap_const_lv7_0,
        inByte5_empty_n => inByte5_empty_n,
        inByte5_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte5_read,
        inByte4_dout => inByte4_dout,
        inByte4_num_data_valid => ap_const_lv7_0,
        inByte4_fifo_cap => ap_const_lv7_0,
        inByte4_empty_n => inByte4_empty_n,
        inByte4_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte4_read,
        inByte3_dout => inByte3_dout,
        inByte3_num_data_valid => ap_const_lv7_0,
        inByte3_fifo_cap => ap_const_lv7_0,
        inByte3_empty_n => inByte3_empty_n,
        inByte3_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte3_read,
        inByte2_dout => inByte2_dout,
        inByte2_num_data_valid => ap_const_lv7_0,
        inByte2_fifo_cap => ap_const_lv7_0,
        inByte2_empty_n => inByte2_empty_n,
        inByte2_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte2_read,
        inByte1_dout => inByte1_dout,
        inByte1_num_data_valid => ap_const_lv7_0,
        inByte1_fifo_cap => ap_const_lv7_0,
        inByte1_empty_n => inByte1_empty_n,
        inByte1_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte1_read,
        inByte0_dout => inByte0_dout,
        inByte0_num_data_valid => ap_const_lv7_0,
        inByte0_fifo_cap => ap_const_lv7_0,
        inByte0_empty_n => inByte0_empty_n,
        inByte0_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte0_read,
        inByte15_dout => inByte15_dout,
        inByte15_num_data_valid => ap_const_lv7_0,
        inByte15_fifo_cap => ap_const_lv7_0,
        inByte15_empty_n => inByte15_empty_n,
        inByte15_read => grp_process_blocks_Pipeline_tail_loop_fu_271_inByte15_read,
        crc_reload => grp_process_blocks_Pipeline_block_loop_fu_199_crc_out,
        sub_ln329 => sub_ln329_reg_523,
        crcTables_0_address0 => grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_address0,
        crcTables_0_ce0 => grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_ce0,
        crcTables_0_q0 => crcTables_0_q0,
        mask_1 => mask_1_reg_512,
        crc_2_out => grp_process_blocks_Pipeline_tail_loop_fu_271_crc_2_out,
        crc_2_out_ap_vld => grp_process_blocks_Pipeline_tail_loop_fu_271_crc_2_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln329_fu_429_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln329_fu_429_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_blocks_Pipeline_block_loop_fu_199_ap_ready = ap_const_logic_1)) then 
                    grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_blocks_Pipeline_tail_loop_fu_271_ap_ready = ap_const_logic_1)) then 
                    grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                c_fu_148 <= ap_const_lv31_0;
            elsif (((icmp_ln329_fu_429_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                c_fu_148 <= add_ln329_fu_434_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                blocks_in_chunk_reg_518 <= blocks_in_chunk_fu_398_p3;
                mask_1_reg_512 <= mask_1_fu_379_p3;
                sub_ln329_reg_523 <= sub_ln329_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                chunkSize_1_reg_482 <= chunkSize_dout;
                crc_size_1_reg_477 <= crc_size_dout;
                icmp_ln325_reg_492 <= icmp_ln325_fu_323_p2;
                init_value_2_reg_472 <= init_value_dout;
                numChunks_2_reg_487 <= numChunks_dout;
                p_lshr_cast_cast_reg_502 <= p_neg_fu_337_p2(31 downto 4);
                p_lshr_f_cast_cast_reg_507 <= chunkSize_dout(31 downto 4);
                tmp_1_reg_497 <= chunkSize_dout(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, outStream_full_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n, ap_CS_fsm_state8, grp_process_blocks_Pipeline_block_loop_fu_199_ap_done, grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done, ap_CS_fsm_state3, icmp_ln329_fu_429_p2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln329_fu_429_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_process_blocks_Pipeline_block_loop_fu_199_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((outStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln329_fu_434_p2 <= std_logic_vector(unsigned(c_fu_148) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if (((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_ap_done)
    begin
        if ((grp_process_blocks_Pipeline_block_loop_fu_199_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done)
    begin
        if ((grp_process_blocks_Pipeline_tail_loop_fu_271_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(outStream_full_n)
    begin
        if ((outStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
                ap_block_state1 <= ((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln329_fu_429_p2)
    begin
        if (((icmp_ln329_fu_429_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln329_fu_429_p2)
    begin
        if (((icmp_ln329_fu_429_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    blocks_in_chunk_fu_398_p3 <= 
        p_neg_t_fu_389_p2 when (tmp_1_reg_497(0) = '1') else 
        p_lshr_f_cast_cast_cast_fu_395_p1;

    chunkSize_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, chunkSize_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            chunkSize_blk_n <= chunkSize_empty_n;
        else 
            chunkSize_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    chunkSize_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            chunkSize_read <= ap_const_logic_1;
        else 
            chunkSize_read <= ap_const_logic_0;
        end if; 
    end process;


    crcTables_0_address0_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_address0, grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            crcTables_0_address0 <= grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            crcTables_0_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_address0;
        else 
            crcTables_0_address0 <= "XXXXXXXX";
        end if; 
    end process;


    crcTables_0_ce0_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_ce0, grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            crcTables_0_ce0 <= grp_process_blocks_Pipeline_tail_loop_fu_271_crcTables_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            crcTables_0_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_0_ce0;
        else 
            crcTables_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    crcTables_10_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_address0;
    crcTables_10_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_10_ce0;
    crcTables_11_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_address0;
    crcTables_11_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_11_ce0;
    crcTables_12_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_address0;
    crcTables_12_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_12_ce0;
    crcTables_13_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_address0;
    crcTables_13_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_13_ce0;
    crcTables_14_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_address0;
    crcTables_14_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_14_ce0;
    crcTables_15_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_address0;
    crcTables_15_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_15_ce0;
    crcTables_1_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_address0;
    crcTables_1_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_1_ce0;
    crcTables_2_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_address0;
    crcTables_2_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_2_ce0;
    crcTables_3_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_address0;
    crcTables_3_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_3_ce0;
    crcTables_4_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_address0;
    crcTables_4_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_4_ce0;
    crcTables_5_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_address0;
    crcTables_5_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_5_ce0;
    crcTables_6_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_address0;
    crcTables_6_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_6_ce0;
    crcTables_7_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_address0;
    crcTables_7_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_7_ce0;
    crcTables_8_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_address0;
    crcTables_8_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_8_ce0;
    crcTables_9_address0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_address0;
    crcTables_9_ce0 <= grp_process_blocks_Pipeline_block_loop_fu_199_crcTables_9_ce0;

    crc_size_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            crc_size_blk_n <= crc_size_empty_n;
        else 
            crc_size_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    crc_size_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            crc_size_read <= ap_const_logic_1;
        else 
            crc_size_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_blocks_Pipeline_block_loop_fu_199_ap_start <= grp_process_blocks_Pipeline_block_loop_fu_199_ap_start_reg;
    grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start <= grp_process_blocks_Pipeline_tail_loop_fu_271_ap_start_reg;
    icmp_ln325_fu_323_p2 <= "1" when (tmp_fu_313_p4 = ap_const_lv27_0) else "0";
    icmp_ln329_fu_429_p2 <= "1" when (signed(zext_ln311_fu_425_p1) < signed(numChunks_2_reg_487)) else "0";

    inByte0_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte0_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte0_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte0_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte0_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte0_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte0_read;
        else 
            inByte0_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte10_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte10_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte10_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte10_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte10_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte10_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte10_read;
        else 
            inByte10_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte11_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte11_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte11_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte11_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte11_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte11_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte11_read;
        else 
            inByte11_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte12_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte12_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte12_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte12_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte12_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte12_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte12_read;
        else 
            inByte12_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte13_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte13_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte13_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte13_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte13_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte13_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte13_read;
        else 
            inByte13_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte14_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte14_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte14_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte14_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte14_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte14_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte14_read;
        else 
            inByte14_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte15_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte15_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte15_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte15_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte15_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte15_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte15_read;
        else 
            inByte15_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte1_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte1_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte1_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte1_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte1_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte1_read;
        else 
            inByte1_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte2_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte2_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte2_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte2_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte2_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte2_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte2_read;
        else 
            inByte2_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte3_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte3_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte3_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte3_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte3_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte3_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte3_read;
        else 
            inByte3_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte4_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte4_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte4_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte4_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte4_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte4_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte4_read;
        else 
            inByte4_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte5_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte5_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte5_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte5_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte5_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte5_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte5_read;
        else 
            inByte5_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte6_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte6_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte6_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte6_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte6_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte6_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte6_read;
        else 
            inByte6_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte7_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte7_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte7_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte7_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte7_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte7_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte7_read;
        else 
            inByte7_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte8_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte8_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte8_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte8_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte8_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte8_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte8_read;
        else 
            inByte8_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte9_read_assign_proc : process(grp_process_blocks_Pipeline_block_loop_fu_199_inByte9_read, grp_process_blocks_Pipeline_tail_loop_fu_271_inByte9_read, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inByte9_read <= grp_process_blocks_Pipeline_tail_loop_fu_271_inByte9_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            inByte9_read <= grp_process_blocks_Pipeline_block_loop_fu_199_inByte9_read;
        else 
            inByte9_read <= ap_const_logic_0;
        end if; 
    end process;


    init_value_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, init_value_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            init_value_blk_n <= init_value_empty_n;
        else 
            init_value_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    init_value_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            init_value_read <= ap_const_logic_1;
        else 
            init_value_read <= ap_const_logic_0;
        end if; 
    end process;

    mask_1_fu_379_p3 <= 
        mask_fu_373_p2 when (icmp_ln325_reg_492(0) = '1') else 
        ap_const_lv32_FFFFFFFF;
    mask_fu_373_p2 <= std_logic_vector(unsigned(shl_ln326_fu_368_p2) + unsigned(ap_const_lv32_FFFFFFFF));

    numChunks_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numChunks_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numChunks_blk_n <= numChunks_empty_n;
        else 
            numChunks_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    numChunks_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numChunks_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numChunks_c_blk_n <= numChunks_c_full_n;
        else 
            numChunks_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numChunks_c_din <= numChunks_dout;

    numChunks_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numChunks_c_write <= ap_const_logic_1;
        else 
            numChunks_c_write <= ap_const_logic_0;
        end if; 
    end process;


    numChunks_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, crc_size_empty_n, init_value_empty_n, numChunks_empty_n, chunkSize_empty_n, numChunks_c_full_n)
    begin
        if ((not(((numChunks_c_full_n = ap_const_logic_0) or (chunkSize_empty_n = ap_const_logic_0) or (numChunks_empty_n = ap_const_logic_0) or (init_value_empty_n = ap_const_logic_0) or (crc_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numChunks_read <= ap_const_logic_1;
        else 
            numChunks_read <= ap_const_logic_0;
        end if; 
    end process;


    outStream_blk_n_assign_proc : process(outStream_full_n, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            outStream_blk_n <= outStream_full_n;
        else 
            outStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outStream_din <= grp_process_blocks_Pipeline_tail_loop_fu_271_crc_2_out;

    outStream_write_assign_proc : process(outStream_full_n, ap_CS_fsm_state8)
    begin
        if (((outStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            outStream_write <= ap_const_logic_1;
        else 
            outStream_write <= ap_const_logic_0;
        end if; 
    end process;

    p_lshr_cast_cast_cast_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_cast_cast_reg_502),29));
    p_lshr_f_cast_cast_cast_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_f_cast_cast_reg_507),29));
    p_neg_fu_337_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(chunkSize_dout));
    p_neg_t_fu_389_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(p_lshr_cast_cast_cast_fu_386_p1));
    shl_ln326_fu_368_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & crc_size_1_reg_477(31-1 downto 0)))));
    shl_ln_fu_409_p3 <= (trunc_ln329_fu_405_p1 & ap_const_lv4_0);
    sub_ln329_fu_417_p2 <= std_logic_vector(unsigned(chunkSize_1_reg_482) - unsigned(shl_ln_fu_409_p3));
    tmp_fu_313_p4 <= crc_size_dout(31 downto 5);
    trunc_ln329_fu_405_p1 <= blocks_in_chunk_fu_398_p3(28 - 1 downto 0);
    zext_ln311_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_148),32));
end behav;
