// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calculate_crc_process_blocks_Pipeline_block_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inByte0_dout,
        inByte0_num_data_valid,
        inByte0_fifo_cap,
        inByte0_empty_n,
        inByte0_read,
        inByte1_dout,
        inByte1_num_data_valid,
        inByte1_fifo_cap,
        inByte1_empty_n,
        inByte1_read,
        inByte2_dout,
        inByte2_num_data_valid,
        inByte2_fifo_cap,
        inByte2_empty_n,
        inByte2_read,
        inByte3_dout,
        inByte3_num_data_valid,
        inByte3_fifo_cap,
        inByte3_empty_n,
        inByte3_read,
        inByte4_dout,
        inByte4_num_data_valid,
        inByte4_fifo_cap,
        inByte4_empty_n,
        inByte4_read,
        inByte5_dout,
        inByte5_num_data_valid,
        inByte5_fifo_cap,
        inByte5_empty_n,
        inByte5_read,
        inByte6_dout,
        inByte6_num_data_valid,
        inByte6_fifo_cap,
        inByte6_empty_n,
        inByte6_read,
        inByte7_dout,
        inByte7_num_data_valid,
        inByte7_fifo_cap,
        inByte7_empty_n,
        inByte7_read,
        inByte8_dout,
        inByte8_num_data_valid,
        inByte8_fifo_cap,
        inByte8_empty_n,
        inByte8_read,
        inByte9_dout,
        inByte9_num_data_valid,
        inByte9_fifo_cap,
        inByte9_empty_n,
        inByte9_read,
        inByte10_dout,
        inByte10_num_data_valid,
        inByte10_fifo_cap,
        inByte10_empty_n,
        inByte10_read,
        inByte11_dout,
        inByte11_num_data_valid,
        inByte11_fifo_cap,
        inByte11_empty_n,
        inByte11_read,
        inByte12_dout,
        inByte12_num_data_valid,
        inByte12_fifo_cap,
        inByte12_empty_n,
        inByte12_read,
        inByte13_dout,
        inByte13_num_data_valid,
        inByte13_fifo_cap,
        inByte13_empty_n,
        inByte13_read,
        inByte14_dout,
        inByte14_num_data_valid,
        inByte14_fifo_cap,
        inByte14_empty_n,
        inByte14_read,
        inByte15_dout,
        inByte15_num_data_valid,
        inByte15_fifo_cap,
        inByte15_empty_n,
        inByte15_read,
        init_value_2,
        blocks_in_chunk,
        crcTables_0_address0,
        crcTables_0_ce0,
        crcTables_0_q0,
        crcTables_1_address0,
        crcTables_1_ce0,
        crcTables_1_q0,
        crcTables_2_address0,
        crcTables_2_ce0,
        crcTables_2_q0,
        crcTables_3_address0,
        crcTables_3_ce0,
        crcTables_3_q0,
        crcTables_4_address0,
        crcTables_4_ce0,
        crcTables_4_q0,
        crcTables_5_address0,
        crcTables_5_ce0,
        crcTables_5_q0,
        crcTables_6_address0,
        crcTables_6_ce0,
        crcTables_6_q0,
        crcTables_7_address0,
        crcTables_7_ce0,
        crcTables_7_q0,
        crcTables_8_address0,
        crcTables_8_ce0,
        crcTables_8_q0,
        crcTables_9_address0,
        crcTables_9_ce0,
        crcTables_9_q0,
        crcTables_10_address0,
        crcTables_10_ce0,
        crcTables_10_q0,
        crcTables_11_address0,
        crcTables_11_ce0,
        crcTables_11_q0,
        crcTables_12_address0,
        crcTables_12_ce0,
        crcTables_12_q0,
        crcTables_13_address0,
        crcTables_13_ce0,
        crcTables_13_q0,
        crcTables_14_address0,
        crcTables_14_ce0,
        crcTables_14_q0,
        crcTables_15_address0,
        crcTables_15_ce0,
        crcTables_15_q0,
        mask_1,
        crc_out,
        crc_out_ap_vld,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inByte0_dout;
input  [6:0] inByte0_num_data_valid;
input  [6:0] inByte0_fifo_cap;
input   inByte0_empty_n;
output   inByte0_read;
input  [7:0] inByte1_dout;
input  [6:0] inByte1_num_data_valid;
input  [6:0] inByte1_fifo_cap;
input   inByte1_empty_n;
output   inByte1_read;
input  [7:0] inByte2_dout;
input  [6:0] inByte2_num_data_valid;
input  [6:0] inByte2_fifo_cap;
input   inByte2_empty_n;
output   inByte2_read;
input  [7:0] inByte3_dout;
input  [6:0] inByte3_num_data_valid;
input  [6:0] inByte3_fifo_cap;
input   inByte3_empty_n;
output   inByte3_read;
input  [7:0] inByte4_dout;
input  [6:0] inByte4_num_data_valid;
input  [6:0] inByte4_fifo_cap;
input   inByte4_empty_n;
output   inByte4_read;
input  [7:0] inByte5_dout;
input  [6:0] inByte5_num_data_valid;
input  [6:0] inByte5_fifo_cap;
input   inByte5_empty_n;
output   inByte5_read;
input  [7:0] inByte6_dout;
input  [6:0] inByte6_num_data_valid;
input  [6:0] inByte6_fifo_cap;
input   inByte6_empty_n;
output   inByte6_read;
input  [7:0] inByte7_dout;
input  [6:0] inByte7_num_data_valid;
input  [6:0] inByte7_fifo_cap;
input   inByte7_empty_n;
output   inByte7_read;
input  [7:0] inByte8_dout;
input  [6:0] inByte8_num_data_valid;
input  [6:0] inByte8_fifo_cap;
input   inByte8_empty_n;
output   inByte8_read;
input  [7:0] inByte9_dout;
input  [6:0] inByte9_num_data_valid;
input  [6:0] inByte9_fifo_cap;
input   inByte9_empty_n;
output   inByte9_read;
input  [7:0] inByte10_dout;
input  [6:0] inByte10_num_data_valid;
input  [6:0] inByte10_fifo_cap;
input   inByte10_empty_n;
output   inByte10_read;
input  [7:0] inByte11_dout;
input  [6:0] inByte11_num_data_valid;
input  [6:0] inByte11_fifo_cap;
input   inByte11_empty_n;
output   inByte11_read;
input  [7:0] inByte12_dout;
input  [6:0] inByte12_num_data_valid;
input  [6:0] inByte12_fifo_cap;
input   inByte12_empty_n;
output   inByte12_read;
input  [7:0] inByte13_dout;
input  [6:0] inByte13_num_data_valid;
input  [6:0] inByte13_fifo_cap;
input   inByte13_empty_n;
output   inByte13_read;
input  [7:0] inByte14_dout;
input  [6:0] inByte14_num_data_valid;
input  [6:0] inByte14_fifo_cap;
input   inByte14_empty_n;
output   inByte14_read;
input  [7:0] inByte15_dout;
input  [6:0] inByte15_num_data_valid;
input  [6:0] inByte15_fifo_cap;
input   inByte15_empty_n;
output   inByte15_read;
input  [31:0] init_value_2;
input  [28:0] blocks_in_chunk;
output  [7:0] crcTables_0_address0;
output   crcTables_0_ce0;
input  [31:0] crcTables_0_q0;
output  [7:0] crcTables_1_address0;
output   crcTables_1_ce0;
input  [31:0] crcTables_1_q0;
output  [7:0] crcTables_2_address0;
output   crcTables_2_ce0;
input  [31:0] crcTables_2_q0;
output  [7:0] crcTables_3_address0;
output   crcTables_3_ce0;
input  [31:0] crcTables_3_q0;
output  [7:0] crcTables_4_address0;
output   crcTables_4_ce0;
input  [31:0] crcTables_4_q0;
output  [7:0] crcTables_5_address0;
output   crcTables_5_ce0;
input  [31:0] crcTables_5_q0;
output  [7:0] crcTables_6_address0;
output   crcTables_6_ce0;
input  [31:0] crcTables_6_q0;
output  [7:0] crcTables_7_address0;
output   crcTables_7_ce0;
input  [31:0] crcTables_7_q0;
output  [7:0] crcTables_8_address0;
output   crcTables_8_ce0;
input  [31:0] crcTables_8_q0;
output  [7:0] crcTables_9_address0;
output   crcTables_9_ce0;
input  [31:0] crcTables_9_q0;
output  [7:0] crcTables_10_address0;
output   crcTables_10_ce0;
input  [31:0] crcTables_10_q0;
output  [7:0] crcTables_11_address0;
output   crcTables_11_ce0;
input  [31:0] crcTables_11_q0;
output  [7:0] crcTables_12_address0;
output   crcTables_12_ce0;
input  [31:0] crcTables_12_q0;
output  [7:0] crcTables_13_address0;
output   crcTables_13_ce0;
input  [31:0] crcTables_13_q0;
output  [7:0] crcTables_14_address0;
output   crcTables_14_ce0;
input  [31:0] crcTables_14_q0;
output  [7:0] crcTables_15_address0;
output   crcTables_15_ce0;
input  [31:0] crcTables_15_q0;
input  [31:0] mask_1;
output  [31:0] crc_out;
output   crc_out_ap_vld;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_idle;
reg inByte0_read;
reg inByte1_read;
reg inByte2_read;
reg inByte3_read;
reg inByte4_read;
reg inByte5_read;
reg inByte6_read;
reg inByte7_read;
reg inByte8_read;
reg inByte9_read;
reg inByte10_read;
reg inByte11_read;
reg inByte12_read;
reg inByte13_read;
reg inByte14_read;
reg inByte15_read;
reg crcTables_0_ce0;
reg crcTables_1_ce0;
reg crcTables_2_ce0;
reg crcTables_3_ce0;
reg crcTables_4_ce0;
reg crcTables_5_ce0;
reg crcTables_6_ce0;
reg crcTables_7_ce0;
reg crcTables_8_ce0;
reg crcTables_9_ce0;
reg crcTables_10_ce0;
reg crcTables_11_ce0;
reg crcTables_12_ce0;
reg crcTables_13_ce0;
reg crcTables_14_ce0;
reg crcTables_15_ce0;
reg crc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln337_fu_486_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    inByte0_blk_n;
wire    ap_block_pp0_stage0;
reg    inByte1_blk_n;
reg    inByte2_blk_n;
reg    inByte3_blk_n;
reg    inByte4_blk_n;
reg    inByte5_blk_n;
reg    inByte6_blk_n;
reg    inByte7_blk_n;
reg    inByte8_blk_n;
reg    inByte9_blk_n;
reg    inByte10_blk_n;
reg    inByte11_blk_n;
reg    inByte12_blk_n;
reg    inByte13_blk_n;
reg    inByte14_blk_n;
reg    inByte15_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln337_reg_768;
wire   [63:0] zext_ln359_fu_516_p1;
wire   [63:0] zext_ln360_fu_537_p1;
wire   [63:0] zext_ln361_fu_558_p1;
wire   [63:0] zext_ln362_fu_579_p1;
wire   [63:0] zext_ln363_fu_584_p1;
wire   [63:0] zext_ln363_1_fu_589_p1;
wire   [63:0] zext_ln364_fu_594_p1;
wire   [63:0] zext_ln364_1_fu_599_p1;
wire   [63:0] zext_ln365_fu_604_p1;
wire   [63:0] zext_ln365_1_fu_609_p1;
wire   [63:0] zext_ln366_fu_614_p1;
wire   [63:0] zext_ln366_1_fu_619_p1;
wire   [63:0] zext_ln367_fu_624_p1;
wire   [63:0] zext_ln367_1_fu_629_p1;
wire   [63:0] zext_ln368_fu_634_p1;
wire   [63:0] zext_ln368_1_fu_639_p1;
reg   [31:0] crc_fu_132;
wire   [31:0] crc_2_fu_734_p2;
reg   [31:0] ap_sig_allocacmp_crc_load;
wire    ap_loop_init;
reg   [27:0] b_fu_136;
wire   [27:0] add_ln331_fu_492_p2;
reg   [27:0] ap_sig_allocacmp_b_load;
reg    ap_block_pp0_stage0_01001;
wire   [28:0] zext_ln337_fu_482_p1;
wire   [7:0] trunc_ln331_fu_506_p1;
wire   [7:0] xor_ln359_fu_510_p2;
wire   [7:0] trunc_ln_fu_521_p4;
wire   [7:0] xor_ln360_fu_531_p2;
wire   [7:0] trunc_ln3_fu_542_p4;
wire   [7:0] xor_ln361_fu_552_p2;
wire   [7:0] trunc_ln4_fu_563_p4;
wire   [7:0] xor_ln362_fu_573_p2;
wire   [31:0] xor_ln370_1_fu_650_p2;
wire   [31:0] xor_ln370_fu_644_p2;
wire   [31:0] xor_ln370_4_fu_668_p2;
wire   [31:0] xor_ln370_3_fu_662_p2;
wire   [31:0] xor_ln370_5_fu_674_p2;
wire   [31:0] xor_ln370_2_fu_656_p2;
wire   [31:0] xor_ln370_8_fu_692_p2;
wire   [31:0] xor_ln370_7_fu_686_p2;
wire   [31:0] xor_ln370_11_fu_710_p2;
wire   [31:0] xor_ln370_10_fu_704_p2;
wire   [31:0] xor_ln370_12_fu_716_p2;
wire   [31:0] xor_ln370_9_fu_698_p2;
wire   [31:0] xor_ln370_13_fu_722_p2;
wire   [31:0] xor_ln370_6_fu_680_p2;
wire   [31:0] xor_ln370_14_fu_728_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_int_blocking_cur_n;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

calculate_crc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln337_fu_486_p2 == 1'd1))) begin
            b_fu_136 <= add_ln331_fu_492_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            b_fu_136 <= 28'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            crc_fu_132 <= init_value_2;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            crc_fu_132 <= crc_2_fu_734_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln337_reg_768 <= icmp_ln337_fu_486_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln337_fu_486_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_b_load = 28'd0;
    end else begin
        ap_sig_allocacmp_b_load = b_fu_136;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_crc_load = crc_2_fu_734_p2;
    end else begin
        ap_sig_allocacmp_crc_load = crc_fu_132;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_0_ce0 = 1'b1;
    end else begin
        crcTables_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_10_ce0 = 1'b1;
    end else begin
        crcTables_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_11_ce0 = 1'b1;
    end else begin
        crcTables_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_12_ce0 = 1'b1;
    end else begin
        crcTables_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_13_ce0 = 1'b1;
    end else begin
        crcTables_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_14_ce0 = 1'b1;
    end else begin
        crcTables_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_15_ce0 = 1'b1;
    end else begin
        crcTables_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_1_ce0 = 1'b1;
    end else begin
        crcTables_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_2_ce0 = 1'b1;
    end else begin
        crcTables_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_3_ce0 = 1'b1;
    end else begin
        crcTables_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_4_ce0 = 1'b1;
    end else begin
        crcTables_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_5_ce0 = 1'b1;
    end else begin
        crcTables_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_6_ce0 = 1'b1;
    end else begin
        crcTables_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_7_ce0 = 1'b1;
    end else begin
        crcTables_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_8_ce0 = 1'b1;
    end else begin
        crcTables_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_9_ce0 = 1'b1;
    end else begin
        crcTables_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln337_reg_768 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crc_out_ap_vld = 1'b1;
    end else begin
        crc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte0_blk_n = inByte0_empty_n;
    end else begin
        inByte0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte0_read = 1'b1;
    end else begin
        inByte0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte10_blk_n = inByte10_empty_n;
    end else begin
        inByte10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte10_read = 1'b1;
    end else begin
        inByte10_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte11_blk_n = inByte11_empty_n;
    end else begin
        inByte11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte11_read = 1'b1;
    end else begin
        inByte11_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte12_blk_n = inByte12_empty_n;
    end else begin
        inByte12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte12_read = 1'b1;
    end else begin
        inByte12_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte13_blk_n = inByte13_empty_n;
    end else begin
        inByte13_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte13_read = 1'b1;
    end else begin
        inByte13_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte14_blk_n = inByte14_empty_n;
    end else begin
        inByte14_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte14_read = 1'b1;
    end else begin
        inByte14_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte15_blk_n = inByte15_empty_n;
    end else begin
        inByte15_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte15_read = 1'b1;
    end else begin
        inByte15_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte1_blk_n = inByte1_empty_n;
    end else begin
        inByte1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte1_read = 1'b1;
    end else begin
        inByte1_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte2_blk_n = inByte2_empty_n;
    end else begin
        inByte2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte2_read = 1'b1;
    end else begin
        inByte2_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte3_blk_n = inByte3_empty_n;
    end else begin
        inByte3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte3_read = 1'b1;
    end else begin
        inByte3_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte4_blk_n = inByte4_empty_n;
    end else begin
        inByte4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte4_read = 1'b1;
    end else begin
        inByte4_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte5_blk_n = inByte5_empty_n;
    end else begin
        inByte5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte5_read = 1'b1;
    end else begin
        inByte5_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte6_blk_n = inByte6_empty_n;
    end else begin
        inByte6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte6_read = 1'b1;
    end else begin
        inByte6_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte7_blk_n = inByte7_empty_n;
    end else begin
        inByte7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte7_read = 1'b1;
    end else begin
        inByte7_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte8_blk_n = inByte8_empty_n;
    end else begin
        inByte8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte8_read = 1'b1;
    end else begin
        inByte8_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inByte9_blk_n = inByte9_empty_n;
    end else begin
        inByte9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inByte9_read = 1'b1;
    end else begin
        inByte9_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln331_fu_492_p2 = (ap_sig_allocacmp_b_load + 28'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inByte7_empty_n == 1'b0) | (inByte6_empty_n == 1'b0) | (inByte5_empty_n == 1'b0) | (inByte4_empty_n == 1'b0) | (inByte3_empty_n == 1'b0) | (inByte2_empty_n == 1'b0) | (inByte1_empty_n == 1'b0) | (inByte0_empty_n == 1'b0) | (inByte15_empty_n == 1'b0) | (inByte14_empty_n == 1'b0) | (inByte13_empty_n == 1'b0) | (inByte12_empty_n == 1'b0) | (inByte11_empty_n == 1'b0) | (inByte10_empty_n == 1'b0) | (inByte9_empty_n == 1'b0) | (inByte8_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inByte7_empty_n == 1'b0) | (inByte6_empty_n == 1'b0) | (inByte5_empty_n == 1'b0) | (inByte4_empty_n == 1'b0) | (inByte3_empty_n == 1'b0) | (inByte2_empty_n == 1'b0) | (inByte1_empty_n == 1'b0) | (inByte0_empty_n == 1'b0) | (inByte15_empty_n == 1'b0) | (inByte14_empty_n == 1'b0) | (inByte13_empty_n == 1'b0) | (inByte12_empty_n == 1'b0) | (inByte11_empty_n == 1'b0) | (inByte10_empty_n == 1'b0) | (inByte9_empty_n == 1'b0) | (inByte8_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inByte7_empty_n == 1'b0) | (inByte6_empty_n == 1'b0) | (inByte5_empty_n == 1'b0) | (inByte4_empty_n == 1'b0) | (inByte3_empty_n == 1'b0) | (inByte2_empty_n == 1'b0) | (inByte1_empty_n == 1'b0) | (inByte0_empty_n == 1'b0) | (inByte15_empty_n == 1'b0) | (inByte14_empty_n == 1'b0) | (inByte13_empty_n == 1'b0) | (inByte12_empty_n == 1'b0) | (inByte11_empty_n == 1'b0) | (inByte10_empty_n == 1'b0) | (inByte9_empty_n == 1'b0) | (inByte8_empty_n == 1'b0)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((inByte7_empty_n == 1'b0) | (inByte6_empty_n == 1'b0) | (inByte5_empty_n == 1'b0) | (inByte4_empty_n == 1'b0) | (inByte3_empty_n == 1'b0) | (inByte2_empty_n == 1'b0) | (inByte1_empty_n == 1'b0) | (inByte0_empty_n == 1'b0) | (inByte15_empty_n == 1'b0) | (inByte14_empty_n == 1'b0) | (inByte13_empty_n == 1'b0) | (inByte12_empty_n == 1'b0) | (inByte11_empty_n == 1'b0) | (inByte10_empty_n == 1'b0) | (inByte9_empty_n == 1'b0) | (inByte8_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_cur_n = (inByte9_blk_n & inByte8_blk_n & inByte7_blk_n & inByte6_blk_n & inByte5_blk_n & inByte4_blk_n & inByte3_blk_n & inByte2_blk_n & inByte1_blk_n & inByte15_blk_n & inByte14_blk_n & inByte13_blk_n & inByte12_blk_n & inByte11_blk_n & inByte10_blk_n & inByte0_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_cur_n & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign crcTables_0_address0 = zext_ln359_fu_516_p1;

assign crcTables_10_address0 = zext_ln366_fu_614_p1;

assign crcTables_11_address0 = zext_ln366_1_fu_619_p1;

assign crcTables_12_address0 = zext_ln367_fu_624_p1;

assign crcTables_13_address0 = zext_ln367_1_fu_629_p1;

assign crcTables_14_address0 = zext_ln368_fu_634_p1;

assign crcTables_15_address0 = zext_ln368_1_fu_639_p1;

assign crcTables_1_address0 = zext_ln360_fu_537_p1;

assign crcTables_2_address0 = zext_ln361_fu_558_p1;

assign crcTables_3_address0 = zext_ln362_fu_579_p1;

assign crcTables_4_address0 = zext_ln363_fu_584_p1;

assign crcTables_5_address0 = zext_ln363_1_fu_589_p1;

assign crcTables_6_address0 = zext_ln364_fu_594_p1;

assign crcTables_7_address0 = zext_ln364_1_fu_599_p1;

assign crcTables_8_address0 = zext_ln365_fu_604_p1;

assign crcTables_9_address0 = zext_ln365_1_fu_609_p1;

assign crc_2_fu_734_p2 = (xor_ln370_14_fu_728_p2 & mask_1);

assign crc_out = crc_fu_132;

assign icmp_ln337_fu_486_p2 = (($signed(zext_ln337_fu_482_p1) < $signed(blocks_in_chunk)) ? 1'b1 : 1'b0);

assign trunc_ln331_fu_506_p1 = ap_sig_allocacmp_crc_load[7:0];

assign trunc_ln3_fu_542_p4 = {{ap_sig_allocacmp_crc_load[23:16]}};

assign trunc_ln4_fu_563_p4 = {{ap_sig_allocacmp_crc_load[31:24]}};

assign trunc_ln_fu_521_p4 = {{ap_sig_allocacmp_crc_load[15:8]}};

assign xor_ln359_fu_510_p2 = (trunc_ln331_fu_506_p1 ^ inByte0_dout);

assign xor_ln360_fu_531_p2 = (trunc_ln_fu_521_p4 ^ inByte1_dout);

assign xor_ln361_fu_552_p2 = (trunc_ln3_fu_542_p4 ^ inByte2_dout);

assign xor_ln362_fu_573_p2 = (trunc_ln4_fu_563_p4 ^ inByte3_dout);

assign xor_ln370_10_fu_704_p2 = (crcTables_13_q0 ^ crcTables_12_q0);

assign xor_ln370_11_fu_710_p2 = (crcTables_15_q0 ^ crcTables_14_q0);

assign xor_ln370_12_fu_716_p2 = (xor_ln370_11_fu_710_p2 ^ xor_ln370_10_fu_704_p2);

assign xor_ln370_13_fu_722_p2 = (xor_ln370_9_fu_698_p2 ^ xor_ln370_12_fu_716_p2);

assign xor_ln370_14_fu_728_p2 = (xor_ln370_6_fu_680_p2 ^ xor_ln370_13_fu_722_p2);

assign xor_ln370_1_fu_650_p2 = (crcTables_3_q0 ^ crcTables_2_q0);

assign xor_ln370_2_fu_656_p2 = (xor_ln370_fu_644_p2 ^ xor_ln370_1_fu_650_p2);

assign xor_ln370_3_fu_662_p2 = (crcTables_5_q0 ^ crcTables_4_q0);

assign xor_ln370_4_fu_668_p2 = (crcTables_7_q0 ^ crcTables_6_q0);

assign xor_ln370_5_fu_674_p2 = (xor_ln370_4_fu_668_p2 ^ xor_ln370_3_fu_662_p2);

assign xor_ln370_6_fu_680_p2 = (xor_ln370_5_fu_674_p2 ^ xor_ln370_2_fu_656_p2);

assign xor_ln370_7_fu_686_p2 = (crcTables_9_q0 ^ crcTables_8_q0);

assign xor_ln370_8_fu_692_p2 = (crcTables_11_q0 ^ crcTables_10_q0);

assign xor_ln370_9_fu_698_p2 = (xor_ln370_8_fu_692_p2 ^ xor_ln370_7_fu_686_p2);

assign xor_ln370_fu_644_p2 = (crcTables_1_q0 ^ crcTables_0_q0);

assign zext_ln337_fu_482_p1 = ap_sig_allocacmp_b_load;

assign zext_ln359_fu_516_p1 = xor_ln359_fu_510_p2;

assign zext_ln360_fu_537_p1 = xor_ln360_fu_531_p2;

assign zext_ln361_fu_558_p1 = xor_ln361_fu_552_p2;

assign zext_ln362_fu_579_p1 = xor_ln362_fu_573_p2;

assign zext_ln363_1_fu_589_p1 = inByte5_dout;

assign zext_ln363_fu_584_p1 = inByte4_dout;

assign zext_ln364_1_fu_599_p1 = inByte7_dout;

assign zext_ln364_fu_594_p1 = inByte6_dout;

assign zext_ln365_1_fu_609_p1 = inByte9_dout;

assign zext_ln365_fu_604_p1 = inByte8_dout;

assign zext_ln366_1_fu_619_p1 = inByte11_dout;

assign zext_ln366_fu_614_p1 = inByte10_dout;

assign zext_ln367_1_fu_629_p1 = inByte13_dout;

assign zext_ln367_fu_624_p1 = inByte12_dout;

assign zext_ln368_1_fu_639_p1 = inByte15_dout;

assign zext_ln368_fu_634_p1 = inByte14_dout;

endmodule //calculate_crc_process_blocks_Pipeline_block_loop
