-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_sha256_sha256_compress_block_Pipeline_round_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_7_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_0_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_1_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_2_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_3_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_4_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_5_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_6_read : IN STD_LOGIC_VECTOR (31 downto 0);
    w_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    w_ce0 : OUT STD_LOGIC;
    w_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    w_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    w_1_ce0 : OUT STD_LOGIC;
    w_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    w_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    w_2_ce0 : OUT STD_LOGIC;
    w_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    h_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_out_ap_vld : OUT STD_LOGIC;
    a_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    a_2_out_ap_vld : OUT STD_LOGIC;
    b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_out_ap_vld : OUT STD_LOGIC;
    c_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_out_ap_vld : OUT STD_LOGIC;
    d_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    d_out_ap_vld : OUT STD_LOGIC;
    f_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_1_out_ap_vld : OUT STD_LOGIC;
    f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_out_ap_vld : OUT STD_LOGIC;
    g_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    g_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of calculate_sha256_sha256_compress_block_Pipeline_round_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv14_AB : STD_LOGIC_VECTOR (13 downto 0) := "00000010101011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln151_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal SHA256_K_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal SHA256_K_ce0 : STD_LOGIC;
    signal SHA256_K_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln151_reg_876 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_reg_876_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal SHA256_K_load_reg_900 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_458_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_reg_905 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln151_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln75_fu_414_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem147_fu_120 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln151_fu_446_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul145_fu_124 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln75_fu_398_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sig_allocacmp_phi_mul145_load : STD_LOGIC_VECTOR (13 downto 0);
    signal d_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal h_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_136 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln151_fu_384_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (6 downto 0);
    signal h_1_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal g_fu_144 : STD_LOGIC_VECTOR (31 downto 0);
    signal f_fu_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal e_1_fu_671_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_1_fu_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_156 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_fu_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_fu_743_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_404_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln151_1_fu_434_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln151_1_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_458_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln54_fu_515_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln54_4_fu_505_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln54_1_fu_529_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln54_5_fu_519_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal xor_ln154_fu_547_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_2_fu_543_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal lshr_ln54_6_fu_533_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln154_1_fu_575_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln154_fu_569_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_553_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln154_1_fu_561_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln154_2_fu_595_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln154_2_fu_581_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln154_3_fu_601_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln154_1_fu_612_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln154_1_fu_589_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln154_2_fu_617_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln154_fu_607_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t1_fu_623_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln164_fu_677_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_3_fu_639_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln54_7_fu_629_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln54_4_fu_653_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln54_8_fu_643_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal and_ln164_fu_683_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln164_1_fu_689_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_5_fu_667_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln54_9_fu_657_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln2_fu_695_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln164_1_fu_703_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln164_2_fu_725_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln164_2_fu_717_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln164_3_fu_731_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln164_fu_737_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln164_1_fu_711_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_sha256_mux_3_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calculate_sha256_sha256_compress_block_Pipeline_round_loop_SHA256_K_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calculate_sha256_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    SHA256_K_U : component calculate_sha256_sha256_compress_block_Pipeline_round_loop_SHA256_K_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => SHA256_K_address0,
        ce0 => SHA256_K_ce0,
        q0 => SHA256_K_q0);

    mux_3_2_32_1_1_U22 : component calculate_sha256_mux_3_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => w_q0,
        din1 => w_1_q0,
        din2 => w_2_q0,
        din3 => tmp_8_fu_458_p4,
        dout => tmp_8_fu_458_p5);

    flow_control_loop_pipe_sequential_init_U : component calculate_sha256_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    b_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    b_fu_160 <= state_0_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    b_fu_160 <= a_fu_743_p2;
                end if;
            end if; 
        end if;
    end process;

    c_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    c_fu_156 <= state_1_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    c_fu_156 <= b_fu_160;
                end if;
            end if; 
        end if;
    end process;

    d_1_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_1_fu_152 <= state_2_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    d_1_fu_152 <= c_fu_156;
                end if;
            end if; 
        end if;
    end process;

    d_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_fu_128 <= state_3_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    d_fu_128 <= d_1_fu_152;
                end if;
            end if; 
        end if;
    end process;

    f_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    f_fu_148 <= state_4_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    f_fu_148 <= e_1_fu_671_p2;
                end if;
            end if; 
        end if;
    end process;

    g_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    g_fu_144 <= state_5_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    g_fu_144 <= f_fu_148;
                end if;
            end if; 
        end if;
    end process;

    h_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_1_fu_140 <= state_6_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    h_1_fu_140 <= g_fu_144;
                end if;
            end if; 
        end if;
    end process;

    h_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    h_fu_132 <= state_7_read;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_0))) then 
                    h_fu_132 <= h_1_fu_140;
                end if;
            end if; 
        end if;
    end process;

    i_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_378_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_136 <= add_ln151_fu_384_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_136 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul145_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_378_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    phi_mul145_fu_124 <= add_ln75_fu_398_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul145_fu_124 <= ap_const_lv14_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem147_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem147_fu_120 <= ap_const_lv7_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln151_reg_876 = ap_const_lv1_0))) then 
                    phi_urem147_fu_120 <= select_ln151_fu_446_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln151_reg_876 = ap_const_lv1_0))) then
                SHA256_K_load_reg_900 <= SHA256_K_q0;
                tmp_8_reg_905 <= tmp_8_fu_458_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln151_reg_876 <= icmp_ln151_fu_378_p2;
                icmp_ln151_reg_876_pp0_iter1_reg <= icmp_ln151_reg_876;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    SHA256_K_address0 <= zext_ln151_fu_393_p1(6 - 1 downto 0);

    SHA256_K_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            SHA256_K_ce0 <= ap_const_logic_1;
        else 
            SHA256_K_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    a_2_out <= b_fu_160;

    a_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            a_2_out_ap_vld <= ap_const_logic_1;
        else 
            a_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    a_fu_743_p2 <= std_logic_vector(unsigned(add_ln164_fu_737_p2) + unsigned(xor_ln164_1_fu_711_p2));
    add_ln151_1_fu_434_p2 <= std_logic_vector(unsigned(phi_urem147_fu_120) + unsigned(ap_const_lv7_1));
    add_ln151_fu_384_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv7_1));
    add_ln154_1_fu_612_p2 <= std_logic_vector(unsigned(tmp_8_reg_905) + unsigned(xor_ln154_3_fu_601_p2));
    add_ln154_2_fu_617_p2 <= std_logic_vector(unsigned(add_ln154_1_fu_612_p2) + unsigned(xor_ln154_1_fu_589_p2));
    add_ln154_fu_607_p2 <= std_logic_vector(unsigned(SHA256_K_load_reg_900) + unsigned(h_fu_132));
    add_ln164_fu_737_p2 <= std_logic_vector(unsigned(t1_fu_623_p2) + unsigned(xor_ln164_3_fu_731_p2));
    add_ln75_fu_398_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul145_load) + unsigned(ap_const_lv14_AB));
    and_ln154_1_fu_575_p2 <= (xor_ln154_fu_547_p2 and h_1_fu_140);
    and_ln154_fu_569_p2 <= (g_fu_144 and f_fu_148);
    and_ln164_1_fu_689_p2 <= (d_1_fu_152 and c_fu_156);
    and_ln164_fu_683_p2 <= (xor_ln164_fu_677_p2 and b_fu_160);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln151_fu_378_p2)
    begin
        if (((icmp_ln151_fu_378_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_136;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul145_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, phi_mul145_fu_124)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_phi_mul145_load <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_phi_mul145_load <= phi_mul145_fu_124;
        end if; 
    end process;

    b_out <= c_fu_156;

    b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            b_out_ap_vld <= ap_const_logic_1;
        else 
            b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_out <= d_1_fu_152;

    c_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            c_out_ap_vld <= ap_const_logic_1;
        else 
            c_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    d_out <= d_fu_128;

    d_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            d_out_ap_vld <= ap_const_logic_1;
        else 
            d_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_1_fu_671_p2 <= std_logic_vector(unsigned(t1_fu_623_p2) + unsigned(d_fu_128));
    f_1_out <= f_fu_148;

    f_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            f_1_out_ap_vld <= ap_const_logic_1;
        else 
            f_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    f_out <= g_fu_144;

    f_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            f_out_ap_vld <= ap_const_logic_1;
        else 
            f_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    g_1_out <= h_1_fu_140;

    g_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            g_1_out_ap_vld <= ap_const_logic_1;
        else 
            g_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    h_out <= h_fu_132;

    h_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln151_reg_876_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln151_reg_876_pp0_iter1_reg = ap_const_lv1_1))) then 
            h_out_ap_vld <= ap_const_logic_1;
        else 
            h_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln151_1_fu_440_p2 <= "1" when (unsigned(add_ln151_1_fu_434_p2) < unsigned(ap_const_lv7_3)) else "0";
    icmp_ln151_fu_378_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv7_40) else "0";
    lshr_ln54_4_fu_505_p4 <= f_fu_148(31 downto 6);
    lshr_ln54_5_fu_519_p4 <= f_fu_148(31 downto 11);
    lshr_ln54_6_fu_533_p4 <= f_fu_148(31 downto 25);
    lshr_ln54_7_fu_629_p4 <= b_fu_160(31 downto 2);
    lshr_ln54_8_fu_643_p4 <= b_fu_160(31 downto 13);
    lshr_ln54_9_fu_657_p4 <= b_fu_160(31 downto 22);
    or_ln154_1_fu_561_p3 <= (trunc_ln54_1_fu_529_p1 & lshr_ln54_5_fu_519_p4);
    or_ln154_2_fu_581_p3 <= (trunc_ln54_2_fu_543_p1 & lshr_ln54_6_fu_533_p4);
    or_ln164_1_fu_703_p3 <= (trunc_ln54_4_fu_653_p1 & lshr_ln54_8_fu_643_p4);
    or_ln164_2_fu_717_p3 <= (trunc_ln54_5_fu_667_p1 & lshr_ln54_9_fu_657_p4);
    or_ln1_fu_553_p3 <= (trunc_ln54_fu_515_p1 & lshr_ln54_4_fu_505_p4);
    or_ln2_fu_695_p3 <= (trunc_ln54_3_fu_639_p1 & lshr_ln54_7_fu_629_p4);
    select_ln151_fu_446_p3 <= 
        add_ln151_1_fu_434_p2 when (icmp_ln151_1_fu_440_p2(0) = '1') else 
        ap_const_lv7_0;
    t1_fu_623_p2 <= std_logic_vector(unsigned(add_ln154_2_fu_617_p2) + unsigned(add_ln154_fu_607_p2));
    tmp_8_fu_458_p4 <= phi_urem147_fu_120(2 - 1 downto 0);
    tmp_fu_404_p4 <= ap_sig_allocacmp_phi_mul145_load(13 downto 9);
    trunc_ln54_1_fu_529_p1 <= f_fu_148(11 - 1 downto 0);
    trunc_ln54_2_fu_543_p1 <= f_fu_148(25 - 1 downto 0);
    trunc_ln54_3_fu_639_p1 <= b_fu_160(2 - 1 downto 0);
    trunc_ln54_4_fu_653_p1 <= b_fu_160(13 - 1 downto 0);
    trunc_ln54_5_fu_667_p1 <= b_fu_160(22 - 1 downto 0);
    trunc_ln54_fu_515_p1 <= f_fu_148(6 - 1 downto 0);
    w_1_address0 <= zext_ln75_fu_414_p1(5 - 1 downto 0);

    w_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_1_ce0 <= ap_const_logic_1;
        else 
            w_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_2_address0 <= zext_ln75_fu_414_p1(5 - 1 downto 0);

    w_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_2_ce0 <= ap_const_logic_1;
        else 
            w_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_address0 <= zext_ln75_fu_414_p1(5 - 1 downto 0);

    w_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w_ce0 <= ap_const_logic_1;
        else 
            w_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln154_1_fu_589_p2 <= (and_ln154_fu_569_p2 xor and_ln154_1_fu_575_p2);
    xor_ln154_2_fu_595_p2 <= (or_ln1_fu_553_p3 xor or_ln154_1_fu_561_p3);
    xor_ln154_3_fu_601_p2 <= (xor_ln154_2_fu_595_p2 xor or_ln154_2_fu_581_p3);
    xor_ln154_fu_547_p2 <= (f_fu_148 xor ap_const_lv32_FFFFFFFF);
    xor_ln164_1_fu_711_p2 <= (and_ln164_fu_683_p2 xor and_ln164_1_fu_689_p2);
    xor_ln164_2_fu_725_p2 <= (or_ln2_fu_695_p3 xor or_ln164_1_fu_703_p3);
    xor_ln164_3_fu_731_p2 <= (xor_ln164_2_fu_725_p2 xor or_ln164_2_fu_717_p3);
    xor_ln164_fu_677_p2 <= (d_1_fu_152 xor c_fu_156);
    zext_ln151_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_5),64));
    zext_ln75_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_404_p4),64));
end behav;
