-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_crc_crc_process_full_blocks is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    crcTables_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_0_ce0 : OUT STD_LOGIC;
    crcTables_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_1_ce0 : OUT STD_LOGIC;
    crcTables_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_2_ce0 : OUT STD_LOGIC;
    crcTables_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_3_ce0 : OUT STD_LOGIC;
    crcTables_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_4_ce0 : OUT STD_LOGIC;
    crcTables_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_5_ce0 : OUT STD_LOGIC;
    crcTables_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_6_ce0 : OUT STD_LOGIC;
    crcTables_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_7_ce0 : OUT STD_LOGIC;
    crcTables_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_8_ce0 : OUT STD_LOGIC;
    crcTables_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_9_ce0 : OUT STD_LOGIC;
    crcTables_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_10_ce0 : OUT STD_LOGIC;
    crcTables_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_11_ce0 : OUT STD_LOGIC;
    crcTables_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_12_ce0 : OUT STD_LOGIC;
    crcTables_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_13_ce0 : OUT STD_LOGIC;
    crcTables_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_14_ce0 : OUT STD_LOGIC;
    crcTables_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    crcTables_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    crcTables_15_ce0 : OUT STD_LOGIC;
    crcTables_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    inByte017_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte017_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte017_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte017_empty_n : IN STD_LOGIC;
    inByte017_read : OUT STD_LOGIC;
    inByte118_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte118_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte118_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte118_empty_n : IN STD_LOGIC;
    inByte118_read : OUT STD_LOGIC;
    inByte219_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte219_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte219_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte219_empty_n : IN STD_LOGIC;
    inByte219_read : OUT STD_LOGIC;
    inByte320_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte320_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte320_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte320_empty_n : IN STD_LOGIC;
    inByte320_read : OUT STD_LOGIC;
    inByte421_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte421_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte421_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte421_empty_n : IN STD_LOGIC;
    inByte421_read : OUT STD_LOGIC;
    inByte522_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte522_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte522_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte522_empty_n : IN STD_LOGIC;
    inByte522_read : OUT STD_LOGIC;
    inByte623_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte623_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte623_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte623_empty_n : IN STD_LOGIC;
    inByte623_read : OUT STD_LOGIC;
    inByte724_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte724_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte724_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte724_empty_n : IN STD_LOGIC;
    inByte724_read : OUT STD_LOGIC;
    inByte825_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte825_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte825_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte825_empty_n : IN STD_LOGIC;
    inByte825_read : OUT STD_LOGIC;
    inByte926_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte926_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte926_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte926_empty_n : IN STD_LOGIC;
    inByte926_read : OUT STD_LOGIC;
    inByte1027_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1027_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1027_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1027_empty_n : IN STD_LOGIC;
    inByte1027_read : OUT STD_LOGIC;
    inByte1128_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1128_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1128_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1128_empty_n : IN STD_LOGIC;
    inByte1128_read : OUT STD_LOGIC;
    inByte1229_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1229_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1229_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1229_empty_n : IN STD_LOGIC;
    inByte1229_read : OUT STD_LOGIC;
    inByte1330_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1330_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1330_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1330_empty_n : IN STD_LOGIC;
    inByte1330_read : OUT STD_LOGIC;
    inByte1431_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1431_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1431_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1431_empty_n : IN STD_LOGIC;
    inByte1431_read : OUT STD_LOGIC;
    inByte1532_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inByte1532_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1532_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    inByte1532_empty_n : IN STD_LOGIC;
    inByte1532_read : OUT STD_LOGIC;
    blocks_in_chunk : IN STD_LOGIC_VECTOR (28 downto 0);
    crc : IN STD_LOGIC_VECTOR (31 downto 0);
    mask : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of calculate_crc_crc_process_full_blocks is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_205_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal empty_reg_231 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln391_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln391_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_idle : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_ready : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte017_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte118_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte219_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte320_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte421_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte522_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte623_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte724_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte825_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte926_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1027_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1128_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1229_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1330_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1431_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1532_read : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_ce0 : STD_LOGIC;
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out_ap_vld : STD_LOGIC;
    signal ap_phi_mux_crc_buf_0_phi_fu_125_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_buf_0_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_crc_crc_process_full_blocks_Pipeline_full_block_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inByte017_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte017_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte017_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte017_empty_n : IN STD_LOGIC;
        inByte017_read : OUT STD_LOGIC;
        inByte118_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte118_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte118_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte118_empty_n : IN STD_LOGIC;
        inByte118_read : OUT STD_LOGIC;
        inByte219_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte219_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte219_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte219_empty_n : IN STD_LOGIC;
        inByte219_read : OUT STD_LOGIC;
        inByte320_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte320_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte320_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte320_empty_n : IN STD_LOGIC;
        inByte320_read : OUT STD_LOGIC;
        inByte421_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte421_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte421_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte421_empty_n : IN STD_LOGIC;
        inByte421_read : OUT STD_LOGIC;
        inByte522_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte522_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte522_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte522_empty_n : IN STD_LOGIC;
        inByte522_read : OUT STD_LOGIC;
        inByte623_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte623_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte623_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte623_empty_n : IN STD_LOGIC;
        inByte623_read : OUT STD_LOGIC;
        inByte724_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte724_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte724_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte724_empty_n : IN STD_LOGIC;
        inByte724_read : OUT STD_LOGIC;
        inByte825_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte825_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte825_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte825_empty_n : IN STD_LOGIC;
        inByte825_read : OUT STD_LOGIC;
        inByte926_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte926_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte926_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte926_empty_n : IN STD_LOGIC;
        inByte926_read : OUT STD_LOGIC;
        inByte1027_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1027_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1027_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1027_empty_n : IN STD_LOGIC;
        inByte1027_read : OUT STD_LOGIC;
        inByte1128_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1128_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1128_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1128_empty_n : IN STD_LOGIC;
        inByte1128_read : OUT STD_LOGIC;
        inByte1229_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1229_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1229_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1229_empty_n : IN STD_LOGIC;
        inByte1229_read : OUT STD_LOGIC;
        inByte1330_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1330_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1330_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1330_empty_n : IN STD_LOGIC;
        inByte1330_read : OUT STD_LOGIC;
        inByte1431_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1431_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1431_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1431_empty_n : IN STD_LOGIC;
        inByte1431_read : OUT STD_LOGIC;
        inByte1532_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inByte1532_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1532_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        inByte1532_empty_n : IN STD_LOGIC;
        inByte1532_read : OUT STD_LOGIC;
        crc : IN STD_LOGIC_VECTOR (31 downto 0);
        blocks_in_chunk : IN STD_LOGIC_VECTOR (27 downto 0);
        crcTables_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_0_ce0 : OUT STD_LOGIC;
        crcTables_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_1_ce0 : OUT STD_LOGIC;
        crcTables_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_2_ce0 : OUT STD_LOGIC;
        crcTables_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_3_ce0 : OUT STD_LOGIC;
        crcTables_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_4_ce0 : OUT STD_LOGIC;
        crcTables_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_5_ce0 : OUT STD_LOGIC;
        crcTables_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_6_ce0 : OUT STD_LOGIC;
        crcTables_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_7_ce0 : OUT STD_LOGIC;
        crcTables_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_8_ce0 : OUT STD_LOGIC;
        crcTables_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_9_ce0 : OUT STD_LOGIC;
        crcTables_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_10_ce0 : OUT STD_LOGIC;
        crcTables_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_11_ce0 : OUT STD_LOGIC;
        crcTables_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_12_ce0 : OUT STD_LOGIC;
        crcTables_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_13_ce0 : OUT STD_LOGIC;
        crcTables_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_14_ce0 : OUT STD_LOGIC;
        crcTables_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        crcTables_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        crcTables_15_ce0 : OUT STD_LOGIC;
        crcTables_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mask : IN STD_LOGIC_VECTOR (31 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131 : component calculate_crc_crc_process_full_blocks_Pipeline_full_block_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start,
        ap_done => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done,
        ap_idle => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_idle,
        ap_ready => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_ready,
        inByte017_dout => inByte017_dout,
        inByte017_num_data_valid => ap_const_lv7_0,
        inByte017_fifo_cap => ap_const_lv7_0,
        inByte017_empty_n => inByte017_empty_n,
        inByte017_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte017_read,
        inByte118_dout => inByte118_dout,
        inByte118_num_data_valid => ap_const_lv7_0,
        inByte118_fifo_cap => ap_const_lv7_0,
        inByte118_empty_n => inByte118_empty_n,
        inByte118_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte118_read,
        inByte219_dout => inByte219_dout,
        inByte219_num_data_valid => ap_const_lv7_0,
        inByte219_fifo_cap => ap_const_lv7_0,
        inByte219_empty_n => inByte219_empty_n,
        inByte219_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte219_read,
        inByte320_dout => inByte320_dout,
        inByte320_num_data_valid => ap_const_lv7_0,
        inByte320_fifo_cap => ap_const_lv7_0,
        inByte320_empty_n => inByte320_empty_n,
        inByte320_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte320_read,
        inByte421_dout => inByte421_dout,
        inByte421_num_data_valid => ap_const_lv7_0,
        inByte421_fifo_cap => ap_const_lv7_0,
        inByte421_empty_n => inByte421_empty_n,
        inByte421_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte421_read,
        inByte522_dout => inByte522_dout,
        inByte522_num_data_valid => ap_const_lv7_0,
        inByte522_fifo_cap => ap_const_lv7_0,
        inByte522_empty_n => inByte522_empty_n,
        inByte522_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte522_read,
        inByte623_dout => inByte623_dout,
        inByte623_num_data_valid => ap_const_lv7_0,
        inByte623_fifo_cap => ap_const_lv7_0,
        inByte623_empty_n => inByte623_empty_n,
        inByte623_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte623_read,
        inByte724_dout => inByte724_dout,
        inByte724_num_data_valid => ap_const_lv7_0,
        inByte724_fifo_cap => ap_const_lv7_0,
        inByte724_empty_n => inByte724_empty_n,
        inByte724_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte724_read,
        inByte825_dout => inByte825_dout,
        inByte825_num_data_valid => ap_const_lv7_0,
        inByte825_fifo_cap => ap_const_lv7_0,
        inByte825_empty_n => inByte825_empty_n,
        inByte825_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte825_read,
        inByte926_dout => inByte926_dout,
        inByte926_num_data_valid => ap_const_lv7_0,
        inByte926_fifo_cap => ap_const_lv7_0,
        inByte926_empty_n => inByte926_empty_n,
        inByte926_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte926_read,
        inByte1027_dout => inByte1027_dout,
        inByte1027_num_data_valid => ap_const_lv7_0,
        inByte1027_fifo_cap => ap_const_lv7_0,
        inByte1027_empty_n => inByte1027_empty_n,
        inByte1027_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1027_read,
        inByte1128_dout => inByte1128_dout,
        inByte1128_num_data_valid => ap_const_lv7_0,
        inByte1128_fifo_cap => ap_const_lv7_0,
        inByte1128_empty_n => inByte1128_empty_n,
        inByte1128_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1128_read,
        inByte1229_dout => inByte1229_dout,
        inByte1229_num_data_valid => ap_const_lv7_0,
        inByte1229_fifo_cap => ap_const_lv7_0,
        inByte1229_empty_n => inByte1229_empty_n,
        inByte1229_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1229_read,
        inByte1330_dout => inByte1330_dout,
        inByte1330_num_data_valid => ap_const_lv7_0,
        inByte1330_fifo_cap => ap_const_lv7_0,
        inByte1330_empty_n => inByte1330_empty_n,
        inByte1330_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1330_read,
        inByte1431_dout => inByte1431_dout,
        inByte1431_num_data_valid => ap_const_lv7_0,
        inByte1431_fifo_cap => ap_const_lv7_0,
        inByte1431_empty_n => inByte1431_empty_n,
        inByte1431_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1431_read,
        inByte1532_dout => inByte1532_dout,
        inByte1532_num_data_valid => ap_const_lv7_0,
        inByte1532_fifo_cap => ap_const_lv7_0,
        inByte1532_empty_n => inByte1532_empty_n,
        inByte1532_read => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1532_read,
        crc => crc,
        blocks_in_chunk => empty_reg_231,
        crcTables_0_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_address0,
        crcTables_0_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_ce0,
        crcTables_0_q0 => crcTables_0_q0,
        crcTables_1_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_address0,
        crcTables_1_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_ce0,
        crcTables_1_q0 => crcTables_1_q0,
        crcTables_2_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_address0,
        crcTables_2_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_ce0,
        crcTables_2_q0 => crcTables_2_q0,
        crcTables_3_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_address0,
        crcTables_3_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_ce0,
        crcTables_3_q0 => crcTables_3_q0,
        crcTables_4_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_address0,
        crcTables_4_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_ce0,
        crcTables_4_q0 => crcTables_4_q0,
        crcTables_5_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_address0,
        crcTables_5_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_ce0,
        crcTables_5_q0 => crcTables_5_q0,
        crcTables_6_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_address0,
        crcTables_6_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_ce0,
        crcTables_6_q0 => crcTables_6_q0,
        crcTables_7_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_address0,
        crcTables_7_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_ce0,
        crcTables_7_q0 => crcTables_7_q0,
        crcTables_8_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_address0,
        crcTables_8_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_ce0,
        crcTables_8_q0 => crcTables_8_q0,
        crcTables_9_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_address0,
        crcTables_9_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_ce0,
        crcTables_9_q0 => crcTables_9_q0,
        crcTables_10_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_address0,
        crcTables_10_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_ce0,
        crcTables_10_q0 => crcTables_10_q0,
        crcTables_11_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_address0,
        crcTables_11_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_ce0,
        crcTables_11_q0 => crcTables_11_q0,
        crcTables_12_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_address0,
        crcTables_12_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_ce0,
        crcTables_12_q0 => crcTables_12_q0,
        crcTables_13_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_address0,
        crcTables_13_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_ce0,
        crcTables_13_q0 => crcTables_13_q0,
        crcTables_14_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_address0,
        crcTables_14_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_ce0,
        crcTables_14_q0 => crcTables_14_q0,
        crcTables_15_address0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_address0,
        crcTables_15_ce0 => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_ce0,
        crcTables_15_q0 => crcTables_15_q0,
        mask => mask,
        p_out => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out,
        p_out_ap_vld => grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_return_preg <= ap_phi_mux_crc_buf_0_phi_fu_125_p4;
                end if; 
            end if;
        end if;
    end process;


    grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (icmp_ln391_fu_210_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_ready = ap_const_logic_1)) then 
                    grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    crc_buf_0_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln391_fu_210_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                crc_buf_0_reg_122 <= crc;
            elsif (((icmp_ln391_reg_242 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                crc_buf_0_reg_122 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_reg_231 <= empty_fu_205_p1;
                icmp_ln391_reg_242 <= icmp_ln391_fu_210_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln391_fu_210_p2, grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (icmp_ln391_fu_210_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_start = ap_const_logic_1) and (icmp_ln391_fu_210_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done)
    begin
        if ((grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_crc_buf_0_phi_fu_125_p4_assign_proc : process(icmp_ln391_reg_242, grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out, crc_buf_0_reg_122, ap_CS_fsm_state3)
    begin
        if (((icmp_ln391_reg_242 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_crc_buf_0_phi_fu_125_p4 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_p_out;
        else 
            ap_phi_mux_crc_buf_0_phi_fu_125_p4 <= crc_buf_0_reg_122;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_crc_buf_0_phi_fu_125_p4, ap_CS_fsm_state3, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_return <= ap_phi_mux_crc_buf_0_phi_fu_125_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    crcTables_0_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_address0;
    crcTables_0_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_0_ce0;
    crcTables_10_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_address0;
    crcTables_10_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_10_ce0;
    crcTables_11_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_address0;
    crcTables_11_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_11_ce0;
    crcTables_12_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_address0;
    crcTables_12_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_12_ce0;
    crcTables_13_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_address0;
    crcTables_13_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_13_ce0;
    crcTables_14_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_address0;
    crcTables_14_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_14_ce0;
    crcTables_15_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_address0;
    crcTables_15_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_15_ce0;
    crcTables_1_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_address0;
    crcTables_1_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_1_ce0;
    crcTables_2_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_address0;
    crcTables_2_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_2_ce0;
    crcTables_3_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_address0;
    crcTables_3_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_3_ce0;
    crcTables_4_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_address0;
    crcTables_4_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_4_ce0;
    crcTables_5_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_address0;
    crcTables_5_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_5_ce0;
    crcTables_6_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_address0;
    crcTables_6_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_6_ce0;
    crcTables_7_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_address0;
    crcTables_7_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_7_ce0;
    crcTables_8_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_address0;
    crcTables_8_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_8_ce0;
    crcTables_9_address0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_address0;
    crcTables_9_ce0 <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_crcTables_9_ce0;
    empty_fu_205_p1 <= blocks_in_chunk(28 - 1 downto 0);
    grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_ap_start_reg;
    icmp_ln391_fu_210_p2 <= "1" when (signed(blocks_in_chunk) > signed(ap_const_lv29_0)) else "0";

    inByte017_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte017_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte017_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte017_read;
        else 
            inByte017_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1027_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1027_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1027_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1027_read;
        else 
            inByte1027_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1128_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1128_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1128_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1128_read;
        else 
            inByte1128_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte118_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte118_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte118_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte118_read;
        else 
            inByte118_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1229_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1229_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1229_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1229_read;
        else 
            inByte1229_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1330_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1330_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1330_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1330_read;
        else 
            inByte1330_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1431_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1431_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1431_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1431_read;
        else 
            inByte1431_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte1532_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1532_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte1532_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte1532_read;
        else 
            inByte1532_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte219_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte219_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte219_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte219_read;
        else 
            inByte219_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte320_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte320_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte320_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte320_read;
        else 
            inByte320_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte421_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte421_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte421_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte421_read;
        else 
            inByte421_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte522_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte522_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte522_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte522_read;
        else 
            inByte522_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte623_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte623_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte623_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte623_read;
        else 
            inByte623_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte724_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte724_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte724_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte724_read;
        else 
            inByte724_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte825_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte825_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte825_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte825_read;
        else 
            inByte825_read <= ap_const_logic_0;
        end if; 
    end process;


    inByte926_read_assign_proc : process(grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte926_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            inByte926_read <= grp_crc_process_full_blocks_Pipeline_full_block_loop_fu_131_inByte926_read;
        else 
            inByte926_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
