// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calculate_sha256_sha256_process_chunk_Pipeline_len_store_double (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln232,
        pad_block_address0,
        pad_block_ce0,
        pad_block_we0,
        pad_block_d0,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [34:0] zext_ln232;
output  [5:0] pad_block_address0;
output   pad_block_ce0;
output   pad_block_we0;
output  [7:0] pad_block_d0;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_idle;
reg pad_block_ce0;
reg pad_block_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln258_fu_71_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln261_1_fu_126_p1;
reg   [3:0] i_fu_36;
wire   [3:0] add_ln258_fu_77_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_2;
wire   [2:0] trunc_ln261_fu_83_p1;
wire   [2:0] xor_ln261_fu_87_p2;
wire   [5:0] shl_ln4_fu_93_p3;
wire   [63:0] zext_ln232_cast_fu_59_p1;
wire   [63:0] zext_ln261_fu_101_p1;
wire   [63:0] lshr_ln261_fu_105_p2;
wire   [3:0] xor_ln261_1_fu_116_p2;
wire  signed [5:0] sext_ln261_fu_122_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

calculate_sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln258_fu_71_p2 == 1'd0)) begin
            i_fu_36 <= add_ln258_fu_77_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_36 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln258_fu_71_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_36;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        pad_block_ce0 = 1'b1;
    end else begin
        pad_block_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln258_fu_71_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        pad_block_we0 = 1'b1;
    end else begin
        pad_block_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln258_fu_77_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign icmp_ln258_fu_71_p2 = ((ap_sig_allocacmp_i_2 == 4'd8) ? 1'b1 : 1'b0);

assign lshr_ln261_fu_105_p2 = zext_ln232_cast_fu_59_p1 >> zext_ln261_fu_101_p1;

assign pad_block_address0 = zext_ln261_1_fu_126_p1;

assign pad_block_d0 = lshr_ln261_fu_105_p2[7:0];

assign sext_ln261_fu_122_p1 = $signed(xor_ln261_1_fu_116_p2);

assign shl_ln4_fu_93_p3 = {{xor_ln261_fu_87_p2}, {3'd0}};

assign trunc_ln261_fu_83_p1 = ap_sig_allocacmp_i_2[2:0];

assign xor_ln261_1_fu_116_p2 = (ap_sig_allocacmp_i_2 ^ 4'd8);

assign xor_ln261_fu_87_p2 = (trunc_ln261_fu_83_p1 ^ 3'd7);

assign zext_ln232_cast_fu_59_p1 = zext_ln232;

assign zext_ln261_1_fu_126_p1 = $unsigned(sext_ln261_fu_122_p1);

assign zext_ln261_fu_101_p1 = shl_ln4_fu_93_p3;

endmodule //calculate_sha256_sha256_process_chunk_Pipeline_len_store_double
