-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calculate_sha256_sha256_compress_block is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_val : IN STD_LOGIC_VECTOR (511 downto 0);
    state_0_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_1_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_2_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_3_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_4_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_5_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_6_read : IN STD_LOGIC_VECTOR (31 downto 0);
    state_7_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of calculate_sha256_sha256_compress_block is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_ce0 : STD_LOGIC;
    signal w_we0 : STD_LOGIC;
    signal w_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_ce1 : STD_LOGIC;
    signal w_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_1_ce0 : STD_LOGIC;
    signal w_1_we0 : STD_LOGIC;
    signal w_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_1_ce1 : STD_LOGIC;
    signal w_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_2_ce0 : STD_LOGIC;
    signal w_2_we0 : STD_LOGIC;
    signal w_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_2_ce1 : STD_LOGIC;
    signal w_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_w_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce1 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce1 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_we0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce1 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_idle : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_ready : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_ce0 : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_h_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_h_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_a_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_a_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_b_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_b_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_c_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_c_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_d_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_d_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_1_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_g_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_g_1_out_ap_vld : STD_LOGIC;
    signal grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln167_fu_208_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln168_fu_213_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln169_fu_218_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln170_fu_223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln171_fu_228_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln172_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln173_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln174_fu_243_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calculate_sha256_sha256_compress_block_Pipeline_init_words IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_2_ce0 : OUT STD_LOGIC;
        w_2_we0 : OUT STD_LOGIC;
        w_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_1_ce0 : OUT STD_LOGIC;
        w_1_we0 : OUT STD_LOGIC;
        w_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_ce0 : OUT STD_LOGIC;
        w_we0 : OUT STD_LOGIC;
        w_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        block_val : IN STD_LOGIC_VECTOR (511 downto 0) );
    end component;


    component calculate_sha256_sha256_compress_block_Pipeline_expand_words IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_2_ce0 : OUT STD_LOGIC;
        w_2_we0 : OUT STD_LOGIC;
        w_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_2_ce1 : OUT STD_LOGIC;
        w_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_1_ce0 : OUT STD_LOGIC;
        w_1_we0 : OUT STD_LOGIC;
        w_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_1_ce1 : OUT STD_LOGIC;
        w_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_ce0 : OUT STD_LOGIC;
        w_we0 : OUT STD_LOGIC;
        w_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_ce1 : OUT STD_LOGIC;
        w_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calculate_sha256_sha256_compress_block_Pipeline_round_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_7_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_0_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_1_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_2_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_3_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_4_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_5_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_6_read : IN STD_LOGIC_VECTOR (31 downto 0);
        w_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_ce0 : OUT STD_LOGIC;
        w_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_1_ce0 : OUT STD_LOGIC;
        w_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        w_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        w_2_ce0 : OUT STD_LOGIC;
        w_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        h_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_out_ap_vld : OUT STD_LOGIC;
        a_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_2_out_ap_vld : OUT STD_LOGIC;
        b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_out_ap_vld : OUT STD_LOGIC;
        c_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_out_ap_vld : OUT STD_LOGIC;
        d_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        d_out_ap_vld : OUT STD_LOGIC;
        f_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        f_1_out_ap_vld : OUT STD_LOGIC;
        f_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        f_out_ap_vld : OUT STD_LOGIC;
        g_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        g_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component calculate_sha256_sha256_compress_block_w_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    w_U : component calculate_sha256_sha256_compress_block_w_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 22,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_address0,
        ce0 => w_ce0,
        we0 => w_we0,
        d0 => w_d0,
        q0 => w_q0,
        address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address1,
        ce1 => w_ce1,
        q1 => w_q1);

    w_1_U : component calculate_sha256_sha256_compress_block_w_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 22,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_1_address0,
        ce0 => w_1_ce0,
        we0 => w_1_we0,
        d0 => w_1_d0,
        q0 => w_1_q0,
        address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address1,
        ce1 => w_1_ce1,
        q1 => w_1_q1);

    w_2_U : component calculate_sha256_sha256_compress_block_w_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 22,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_2_address0,
        ce0 => w_2_ce0,
        we0 => w_2_we0,
        d0 => w_2_d0,
        q0 => w_2_q0,
        address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address1,
        ce1 => w_2_ce1,
        q1 => w_2_q1);

    grp_sha256_compress_block_Pipeline_init_words_fu_132 : component calculate_sha256_sha256_compress_block_Pipeline_init_words
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start,
        ap_done => grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done,
        ap_idle => grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_idle,
        ap_ready => grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_ready,
        w_2_address0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_address0,
        w_2_ce0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_ce0,
        w_2_we0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_we0,
        w_2_d0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_d0,
        w_1_address0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_address0,
        w_1_ce0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_ce0,
        w_1_we0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_we0,
        w_1_d0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_d0,
        w_address0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_address0,
        w_ce0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_ce0,
        w_we0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_we0,
        w_d0 => grp_sha256_compress_block_Pipeline_init_words_fu_132_w_d0,
        block_val => block_val);

    grp_sha256_compress_block_Pipeline_expand_words_fu_144 : component calculate_sha256_sha256_compress_block_Pipeline_expand_words
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start,
        ap_done => grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done,
        ap_idle => grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_idle,
        ap_ready => grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_ready,
        w_2_address0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address0,
        w_2_ce0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce0,
        w_2_we0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_we0,
        w_2_d0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_d0,
        w_2_q0 => w_2_q0,
        w_2_address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address1,
        w_2_ce1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce1,
        w_2_q1 => w_2_q1,
        w_1_address0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address0,
        w_1_ce0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce0,
        w_1_we0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_we0,
        w_1_d0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_d0,
        w_1_q0 => w_1_q0,
        w_1_address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address1,
        w_1_ce1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce1,
        w_1_q1 => w_1_q1,
        w_address0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address0,
        w_ce0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce0,
        w_we0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_we0,
        w_d0 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_d0,
        w_q0 => w_q0,
        w_address1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address1,
        w_ce1 => grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce1,
        w_q1 => w_q1);

    grp_sha256_compress_block_Pipeline_round_loop_fu_151 : component calculate_sha256_sha256_compress_block_Pipeline_round_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start,
        ap_done => grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done,
        ap_idle => grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_idle,
        ap_ready => grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_ready,
        state_7_read => state_7_read,
        state_0_read => state_0_read,
        state_1_read => state_1_read,
        state_2_read => state_2_read,
        state_3_read => state_3_read,
        state_4_read => state_4_read,
        state_5_read => state_5_read,
        state_6_read => state_6_read,
        w_address0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_address0,
        w_ce0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_ce0,
        w_q0 => w_q0,
        w_1_address0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_address0,
        w_1_ce0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_ce0,
        w_1_q0 => w_1_q0,
        w_2_address0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_address0,
        w_2_ce0 => grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_ce0,
        w_2_q0 => w_2_q0,
        h_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_h_out,
        h_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_h_out_ap_vld,
        a_2_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_a_2_out,
        a_2_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_a_2_out_ap_vld,
        b_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_b_out,
        b_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_b_out_ap_vld,
        c_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_c_out,
        c_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_c_out_ap_vld,
        d_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_d_out,
        d_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_d_out_ap_vld,
        f_1_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_1_out,
        f_1_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_1_out_ap_vld,
        f_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_out,
        f_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_out_ap_vld,
        g_1_out => grp_sha256_compress_block_Pipeline_round_loop_fu_151_g_1_out,
        g_1_out_ap_vld => grp_sha256_compress_block_Pipeline_round_loop_fu_151_g_1_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done, grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done, grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln167_fu_208_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_a_2_out) + unsigned(state_0_read));
    add_ln168_fu_213_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_b_out) + unsigned(state_1_read));
    add_ln169_fu_218_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_c_out) + unsigned(state_2_read));
    add_ln170_fu_223_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_d_out) + unsigned(state_3_read));
    add_ln171_fu_228_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_1_out) + unsigned(state_4_read));
    add_ln172_fu_233_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_f_out) + unsigned(state_5_read));
    add_ln173_fu_238_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_g_1_out) + unsigned(state_6_read));
    add_ln174_fu_243_p2 <= std_logic_vector(unsigned(grp_sha256_compress_block_Pipeline_round_loop_fu_151_h_out) + unsigned(state_7_read));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done)
    begin
        if ((grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done)
    begin
        if ((grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done)
    begin
        if ((grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln167_fu_208_p2;
    ap_return_1 <= add_ln168_fu_213_p2;
    ap_return_2 <= add_ln169_fu_218_p2;
    ap_return_3 <= add_ln170_fu_223_p2;
    ap_return_4 <= add_ln171_fu_228_p2;
    ap_return_5 <= add_ln172_fu_233_p2;
    ap_return_6 <= add_ln173_fu_238_p2;
    ap_return_7 <= add_ln174_fu_243_p2;
    grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_ap_start_reg;
    grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start <= grp_sha256_compress_block_Pipeline_init_words_fu_132_ap_start_reg;
    grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_ap_start_reg;

    w_1_address0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_address0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_1_address0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_1_address0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_1_address0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_address0;
        else 
            w_1_address0 <= "XXXXX";
        end if; 
    end process;


    w_1_ce0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_ce0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_1_ce0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_1_ce0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_1_ce0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_ce0;
        else 
            w_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    w_1_ce1_assign_proc : process(grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_1_ce1 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_ce1;
        else 
            w_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    w_1_d0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_d0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_1_d0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_1_d0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_d0;
        else 
            w_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    w_1_we0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_we0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_1_we0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_1_we0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_1_we0;
        else 
            w_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    w_2_address0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_address0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_2_address0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_2_address0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_2_address0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_address0;
        else 
            w_2_address0 <= "XXXXX";
        end if; 
    end process;


    w_2_ce0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_ce0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_2_ce0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_2_ce0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_2_ce0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_ce0;
        else 
            w_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    w_2_ce1_assign_proc : process(grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_2_ce1 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_ce1;
        else 
            w_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    w_2_d0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_d0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_2_d0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_2_d0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_d0;
        else 
            w_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    w_2_we0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_we0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_2_we0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_2_we0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_2_we0;
        else 
            w_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    w_address0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_address0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_address0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_address0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_address0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_address0;
        else 
            w_address0 <= "XXXXX";
        end if; 
    end process;


    w_ce0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_ce0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce0, grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            w_ce0 <= grp_sha256_compress_block_Pipeline_round_loop_fu_151_w_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_ce0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_ce0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_ce0;
        else 
            w_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    w_ce1_assign_proc : process(grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_ce1 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_ce1;
        else 
            w_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    w_d0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_d0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_d0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_d0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_d0;
        else 
            w_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    w_we0_assign_proc : process(grp_sha256_compress_block_Pipeline_init_words_fu_132_w_we0, grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            w_we0 <= grp_sha256_compress_block_Pipeline_expand_words_fu_144_w_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            w_we0 <= grp_sha256_compress_block_Pipeline_init_words_fu_132_w_we0;
        else 
            w_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
