// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module calculate_crc_load_crc_tables_Pipeline_load_lut_rows_load_lut_cols (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        sext_ln365,
        crcTables_0_address0,
        crcTables_0_ce0,
        crcTables_0_we0,
        crcTables_0_d0,
        crcTables_1_address0,
        crcTables_1_ce0,
        crcTables_1_we0,
        crcTables_1_d0,
        crcTables_2_address0,
        crcTables_2_ce0,
        crcTables_2_we0,
        crcTables_2_d0,
        crcTables_3_address0,
        crcTables_3_ce0,
        crcTables_3_we0,
        crcTables_3_d0,
        crcTables_4_address0,
        crcTables_4_ce0,
        crcTables_4_we0,
        crcTables_4_d0,
        crcTables_5_address0,
        crcTables_5_ce0,
        crcTables_5_we0,
        crcTables_5_d0,
        crcTables_6_address0,
        crcTables_6_ce0,
        crcTables_6_we0,
        crcTables_6_d0,
        crcTables_7_address0,
        crcTables_7_ce0,
        crcTables_7_we0,
        crcTables_7_d0,
        crcTables_8_address0,
        crcTables_8_ce0,
        crcTables_8_we0,
        crcTables_8_d0,
        crcTables_9_address0,
        crcTables_9_ce0,
        crcTables_9_we0,
        crcTables_9_d0,
        crcTables_10_address0,
        crcTables_10_ce0,
        crcTables_10_we0,
        crcTables_10_d0,
        crcTables_11_address0,
        crcTables_11_ce0,
        crcTables_11_we0,
        crcTables_11_d0,
        crcTables_12_address0,
        crcTables_12_ce0,
        crcTables_12_we0,
        crcTables_12_d0,
        crcTables_13_address0,
        crcTables_13_ce0,
        crcTables_13_we0,
        crcTables_13_d0,
        crcTables_14_address0,
        crcTables_14_ce0,
        crcTables_14_we0,
        crcTables_14_d0,
        crcTables_15_address0,
        crcTables_15_ce0,
        crcTables_15_we0,
        crcTables_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [511:0] m_axi_gmem1_WDATA;
output  [63:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [511:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [57:0] sext_ln365;
output  [7:0] crcTables_0_address0;
output   crcTables_0_ce0;
output   crcTables_0_we0;
output  [31:0] crcTables_0_d0;
output  [7:0] crcTables_1_address0;
output   crcTables_1_ce0;
output   crcTables_1_we0;
output  [31:0] crcTables_1_d0;
output  [7:0] crcTables_2_address0;
output   crcTables_2_ce0;
output   crcTables_2_we0;
output  [31:0] crcTables_2_d0;
output  [7:0] crcTables_3_address0;
output   crcTables_3_ce0;
output   crcTables_3_we0;
output  [31:0] crcTables_3_d0;
output  [7:0] crcTables_4_address0;
output   crcTables_4_ce0;
output   crcTables_4_we0;
output  [31:0] crcTables_4_d0;
output  [7:0] crcTables_5_address0;
output   crcTables_5_ce0;
output   crcTables_5_we0;
output  [31:0] crcTables_5_d0;
output  [7:0] crcTables_6_address0;
output   crcTables_6_ce0;
output   crcTables_6_we0;
output  [31:0] crcTables_6_d0;
output  [7:0] crcTables_7_address0;
output   crcTables_7_ce0;
output   crcTables_7_we0;
output  [31:0] crcTables_7_d0;
output  [7:0] crcTables_8_address0;
output   crcTables_8_ce0;
output   crcTables_8_we0;
output  [31:0] crcTables_8_d0;
output  [7:0] crcTables_9_address0;
output   crcTables_9_ce0;
output   crcTables_9_we0;
output  [31:0] crcTables_9_d0;
output  [7:0] crcTables_10_address0;
output   crcTables_10_ce0;
output   crcTables_10_we0;
output  [31:0] crcTables_10_d0;
output  [7:0] crcTables_11_address0;
output   crcTables_11_ce0;
output   crcTables_11_we0;
output  [31:0] crcTables_11_d0;
output  [7:0] crcTables_12_address0;
output   crcTables_12_ce0;
output   crcTables_12_we0;
output  [31:0] crcTables_12_d0;
output  [7:0] crcTables_13_address0;
output   crcTables_13_ce0;
output   crcTables_13_we0;
output  [31:0] crcTables_13_d0;
output  [7:0] crcTables_14_address0;
output   crcTables_14_ce0;
output   crcTables_14_we0;
output  [31:0] crcTables_14_d0;
output  [7:0] crcTables_15_address0;
output   crcTables_15_ce0;
output   crcTables_15_we0;
output  [31:0] crcTables_15_d0;

reg ap_idle;
reg m_axi_gmem1_RREADY;
reg crcTables_0_ce0;
reg crcTables_0_we0;
reg crcTables_1_ce0;
reg crcTables_1_we0;
reg crcTables_2_ce0;
reg crcTables_2_we0;
reg crcTables_3_ce0;
reg crcTables_3_we0;
reg crcTables_4_ce0;
reg crcTables_4_we0;
reg crcTables_5_ce0;
reg crcTables_5_we0;
reg crcTables_6_ce0;
reg crcTables_6_we0;
reg crcTables_7_ce0;
reg crcTables_7_we0;
reg crcTables_8_ce0;
reg crcTables_8_we0;
reg crcTables_9_ce0;
reg crcTables_9_we0;
reg crcTables_10_ce0;
reg crcTables_10_we0;
reg crcTables_11_ce0;
reg crcTables_11_we0;
reg crcTables_12_ce0;
reg crcTables_12_we0;
reg crcTables_13_ce0;
reg crcTables_13_we0;
reg crcTables_14_ce0;
reg crcTables_14_we0;
reg crcTables_15_ce0;
reg crcTables_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln365_reg_597;
reg   [0:0] icmp_ln371_reg_612;
reg    ap_predicate_op47_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln365_fu_409_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln365_reg_597_pp0_iter1_reg;
wire   [0:0] icmp_ln368_fu_424_p2;
reg   [0:0] icmp_ln368_reg_601;
reg   [0:0] icmp_ln368_reg_601_pp0_iter1_reg;
wire   [8:0] select_ln365_fu_430_p3;
reg   [8:0] select_ln365_reg_607;
reg   [8:0] select_ln365_reg_607_pp0_iter1_reg;
wire   [0:0] icmp_ln371_fu_442_p2;
reg   [0:0] icmp_ln371_reg_612_pp0_iter1_reg;
reg   [511:0] gmem1_addr_read_reg_616;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [511:0] ap_phi_mux_empty_phi_fu_376_p4;
wire   [511:0] ap_phi_reg_pp0_iter2_empty_reg_373;
wire   [511:0] zext_ln368_fu_500_p1;
wire   [63:0] zext_ln368_1_fu_505_p1;
reg   [479:0] shiftreg_fu_138;
wire    ap_loop_init;
reg   [8:0] j_fu_142;
wire   [8:0] add_ln368_fu_448_p2;
reg   [8:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_146;
wire   [4:0] select_ln365_2_fu_489_p3;
reg   [12:0] indvar_flatten_fu_150;
wire   [12:0] add_ln365_fu_415_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [3:0] trunc_ln365_fu_496_p1;
wire   [31:0] trunc_ln371_fu_524_p1;
wire   [3:0] trunc_ln368_fu_438_p1;
wire   [4:0] add_ln365_1_fu_483_p2;
wire   [479:0] select_ln365_1_fu_476_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

calculate_crc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_fu_146 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_146 <= select_ln365_2_fu_489_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln365_fu_409_p2 == 1'd0))) begin
            indvar_flatten_fu_150 <= add_ln365_fu_415_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_150 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln365_fu_409_p2 == 1'd0))) begin
            j_fu_142 <= add_ln368_fu_448_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_142 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            shiftreg_fu_138 <= 480'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            shiftreg_fu_138 <= {{ap_phi_mux_empty_phi_fu_376_p4[511:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln365_reg_597 <= icmp_ln365_fu_409_p2;
        icmp_ln365_reg_597_pp0_iter1_reg <= icmp_ln365_reg_597;
        icmp_ln368_reg_601_pp0_iter1_reg <= icmp_ln368_reg_601;
        icmp_ln371_reg_612_pp0_iter1_reg <= icmp_ln371_reg_612;
        select_ln365_reg_607_pp0_iter1_reg <= select_ln365_reg_607;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op47_read_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem1_addr_read_reg_616 <= m_axi_gmem1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln365_fu_409_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln368_reg_601 <= icmp_ln368_fu_424_p2;
        icmp_ln371_reg_612 <= icmp_ln371_fu_442_p2;
        select_ln365_reg_607 <= select_ln365_fu_430_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln365_fu_409_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln365_reg_597 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln365_reg_597_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln371_reg_612_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_empty_phi_fu_376_p4 = zext_ln368_fu_500_p1;
        end else if ((icmp_ln371_reg_612_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_empty_phi_fu_376_p4 = gmem1_addr_read_reg_616;
        end else begin
            ap_phi_mux_empty_phi_fu_376_p4 = ap_phi_reg_pp0_iter2_empty_reg_373;
        end
    end else begin
        ap_phi_mux_empty_phi_fu_376_p4 = ap_phi_reg_pp0_iter2_empty_reg_373;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_150;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 9'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_142;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_0_ce0 = 1'b1;
    end else begin
        crcTables_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_0_we0 = 1'b1;
    end else begin
        crcTables_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_10_ce0 = 1'b1;
    end else begin
        crcTables_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd10) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_10_we0 = 1'b1;
    end else begin
        crcTables_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_11_ce0 = 1'b1;
    end else begin
        crcTables_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_11_we0 = 1'b1;
    end else begin
        crcTables_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_12_ce0 = 1'b1;
    end else begin
        crcTables_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd12) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_12_we0 = 1'b1;
    end else begin
        crcTables_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_13_ce0 = 1'b1;
    end else begin
        crcTables_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd13) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_13_we0 = 1'b1;
    end else begin
        crcTables_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_14_ce0 = 1'b1;
    end else begin
        crcTables_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd14) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_14_we0 = 1'b1;
    end else begin
        crcTables_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_15_ce0 = 1'b1;
    end else begin
        crcTables_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_15_we0 = 1'b1;
    end else begin
        crcTables_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_1_ce0 = 1'b1;
    end else begin
        crcTables_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_1_we0 = 1'b1;
    end else begin
        crcTables_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_2_ce0 = 1'b1;
    end else begin
        crcTables_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_2_we0 = 1'b1;
    end else begin
        crcTables_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_3_ce0 = 1'b1;
    end else begin
        crcTables_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_3_we0 = 1'b1;
    end else begin
        crcTables_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_4_ce0 = 1'b1;
    end else begin
        crcTables_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_4_we0 = 1'b1;
    end else begin
        crcTables_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_5_ce0 = 1'b1;
    end else begin
        crcTables_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_5_we0 = 1'b1;
    end else begin
        crcTables_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_6_ce0 = 1'b1;
    end else begin
        crcTables_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_6_we0 = 1'b1;
    end else begin
        crcTables_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_7_ce0 = 1'b1;
    end else begin
        crcTables_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_7_we0 = 1'b1;
    end else begin
        crcTables_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_8_ce0 = 1'b1;
    end else begin
        crcTables_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd8) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_8_we0 = 1'b1;
    end else begin
        crcTables_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_9_ce0 = 1'b1;
    end else begin
        crcTables_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln365_fu_496_p1 == 4'd9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        crcTables_9_we0 = 1'b1;
    end else begin
        crcTables_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op47_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op47_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln365_1_fu_483_p2 = (i_fu_146 + 5'd1);

assign add_ln365_fu_415_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln368_fu_448_p2 = (select_ln365_fu_430_p3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op47_read_state2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op47_read_state2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op47_read_state2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter2_empty_reg_373 = 'bx;

always @ (*) begin
    ap_predicate_op47_read_state2 = ((icmp_ln371_reg_612 == 1'd1) & (icmp_ln365_reg_597 == 1'd0));
end

assign crcTables_0_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_0_d0 = trunc_ln371_fu_524_p1;

assign crcTables_10_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_10_d0 = trunc_ln371_fu_524_p1;

assign crcTables_11_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_11_d0 = trunc_ln371_fu_524_p1;

assign crcTables_12_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_12_d0 = trunc_ln371_fu_524_p1;

assign crcTables_13_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_13_d0 = trunc_ln371_fu_524_p1;

assign crcTables_14_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_14_d0 = trunc_ln371_fu_524_p1;

assign crcTables_15_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_15_d0 = trunc_ln371_fu_524_p1;

assign crcTables_1_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_1_d0 = trunc_ln371_fu_524_p1;

assign crcTables_2_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_2_d0 = trunc_ln371_fu_524_p1;

assign crcTables_3_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_3_d0 = trunc_ln371_fu_524_p1;

assign crcTables_4_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_4_d0 = trunc_ln371_fu_524_p1;

assign crcTables_5_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_5_d0 = trunc_ln371_fu_524_p1;

assign crcTables_6_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_6_d0 = trunc_ln371_fu_524_p1;

assign crcTables_7_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_7_d0 = trunc_ln371_fu_524_p1;

assign crcTables_8_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_8_d0 = trunc_ln371_fu_524_p1;

assign crcTables_9_address0 = zext_ln368_1_fu_505_p1;

assign crcTables_9_d0 = trunc_ln371_fu_524_p1;

assign icmp_ln365_fu_409_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln368_fu_424_p2 = ((ap_sig_allocacmp_j_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln371_fu_442_p2 = ((trunc_ln368_fu_438_p1 == 4'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 512'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 64'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign select_ln365_1_fu_476_p3 = ((icmp_ln368_reg_601_pp0_iter1_reg[0:0] == 1'b1) ? 480'd0 : shiftreg_fu_138);

assign select_ln365_2_fu_489_p3 = ((icmp_ln368_reg_601_pp0_iter1_reg[0:0] == 1'b1) ? add_ln365_1_fu_483_p2 : i_fu_146);

assign select_ln365_fu_430_p3 = ((icmp_ln368_fu_424_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln365_fu_496_p1 = select_ln365_2_fu_489_p3[3:0];

assign trunc_ln368_fu_438_p1 = select_ln365_fu_430_p3[3:0];

assign trunc_ln371_fu_524_p1 = ap_phi_mux_empty_phi_fu_376_p4[31:0];

assign zext_ln368_1_fu_505_p1 = select_ln365_reg_607_pp0_iter1_reg;

assign zext_ln368_fu_500_p1 = select_ln365_1_fu_476_p3;

endmodule //calculate_crc_load_crc_tables_Pipeline_load_lut_rows_load_lut_cols
